### ISSUE TITLE
Issues when installing On SIFT - Ubuntu 16.04

### ISSUE THREAD

**Issue by savir210** [REMnux/remnux-cli#1]
remnux-cli@1.0.2-master.a4d0624
remnux-version: notinstalled

downloading undefined
downloading remnux-salt-states-undefined.tar.gz.asc
downloading remnux-salt-states-undefined.tar.gz.sha256
downloading remnux-salt-states-undefined.tar.gz.sha256.asc
downloading remnux-salt-states-undefined.tar.gz
validating file remnux-salt-states-undefined.tar.gz

Hashes for remnux-salt-states-undefined.tar.gz do not match. Expected: , Actual: 395408a3dc9c3db2b5c200b8722a13a60898c861633b99e6e250186adffd1370  /tmp/remnux-salt-states-undefined.tar.gz

Error: Hashes for remnux-salt-states-undefined.tar.gz do not match. Expected: , Actual: 395408a3dc9c3db2b5c200b8722a13a60898c861633b99e6e250186adffd1370  /tmp/remnux-salt-states-undefined.tar.gz

    at Object.<anonymous> (/snapshot/cli/remnux-cli.js:354:13)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/snapshot/cli/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn.module.exports.PromiseSpawn._promiseFulfilled (/snapshot/cli/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise.module.exports.Promise._settlePromise (/snapshot/cli/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/snapshot/cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/snapshot/cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/snapshot/cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.__dirname.Async.drainQueues (/snapshot/cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by lennyzeltser** [comment]
At the moment REMnux is only compatible with Ubuntu 14.04. I'm working on a version that will be compatible with 16.04.
