### ISSUE TITLE
Instand CLI crash when attempting to upgrade from 2022.39.2 to 2022.44.5

### ISSUE THREAD

**Issue by seanthegeek** [REMnux/remnux-cli#103]
I'm getting errors when I try to update an addon REMnux install from 2022.39.2 to 2022.44.5 on fully patched Xubuntu 20.04 LTS. Previous REMnux upgrades have worked without issues.

## CLI output

```text
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: v2022.39.2

> downloading v2022.44.5
>> downloading remnux-salt-states-v2022.44.5.tar.gz.asc
>> downloading remnux-salt-states-v2022.44.5.tar.gz.sha256
>> downloading remnux-salt-states-v2022.44.5.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2022.44.5.tar.gz
> validating file remnux-salt-states-v2022.44.5.tar.gz
> validating signature for remnux-salt-states-v2022.44.5.tar.gz.sha256
> extracting update remnux-salt-states-v2022.44.5.tar.gz
> using previous mode: addon
> upgrading/updating to v2022.44.5
>> Log file: /var/cache/remnux/cli/v2022.44.5/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

## saltstack.log

```text
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: remnux
[DEBUG   ] Using importlib_metadata to load entry points
[ERROR   ] 'EntryPoints' object has no attribute 'items'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 210, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 887, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/usr/lib/python3/dist-packages/salt/log/setup.py", line 414, in setup_extended_logging
    providers = salt.loader.log_handlers(opts)
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 686, in log_handlers
    _module_dirs(
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 148, in _module_dirs
    for entry_point in entrypoints.iter_entry_points("salt.loader"):
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 43, in _wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 62, in iter_entry_points
    for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
Usage: salt-call [options] <function> [arguments]

salt-call: error: Error while processing <function LogLevelMixIn.__setup_extended_logging at 0x7f73cf9c18b0>: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 210, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 887, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/usr/lib/python3/dist-packages/salt/log/setup.py", line 414, in setup_extended_logging
    providers = salt.loader.log_handlers(opts)
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 686, in log_handlers
    _module_dirs(
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 148, in _module_dirs
    for entry_point in entrypoints.iter_entry_points("salt.loader"):
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 43, in _wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 62, in iter_entry_points
    for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
```

**Comment by digitalsleuth** [comment]
Hi @seanthegeek , the issue you're receiving is due to a recent update in the importlib-metadata python package.

To avoid this issue, you can run the following:
`sudo python3 -m pip install "importlib-metadata<5.0.0"`

Then re-run the CLI installer.

**Comment by seanthegeek** [comment]
Thanks @digitalsleuth! That worked. How did you figure that out?

**Comment by digitalsleuth** [comment]
Hey @seanthegeek , sorry for the delay in getting back to you. I've come across this a few times, and it's actually an issue identified at the [SaltStack GitHub Issues Page](https://github.com/saltstack/salt/pull/62854). Once the next version which supports this change is released, I'm sure we can find a way to include this fix in a more permanent way.

Cheers!
