### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by faisalusuf** [REMnux/remnux-cli#117]
Hello,
On a fresh deployment of Remnux on Virtualbox the upgrade is failing. The internet connectivity ran into issue during the upgrade process. Now the upgrade is not getting resumed, throwing error:

```
`emnux@remnux:/var/cache/remnux/cli/v2023.7.1$ remnux upgrade
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: v2021.15.2

> downloading v2023.7.1
>> downloading remnux-salt-states-v2023.7.1.tar.gz.asc
>> downloading remnux-salt-states-v2023.7.1.tar.gz.sha256
>> downloading remnux-salt-states-v2023.7.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2023.7.1.tar.gz
> validating file remnux-salt-states-v2023.7.1.tar.gz
> validating signature for remnux-salt-states-v2023.7.1.tar.gz.sha256
> extracting update remnux-salt-states-v2023.7.1.tar.gz
> using previous mode: dedicated
> upgrading/updating to v2023.7.1
>> Log file: /var/cache/remnux/cli/v2023.7.1/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
`
```
Saltstack log:
```
[`remnux@remnux:/var/cache/remnux/cli/v2023.7.1$ cat saltstack.log
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: remnux
[DEBUG   ] Using importlib_metadata to load entry points
[ERROR   ] 'EntryPoints' object has no attribute 'items'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 210, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 887, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/usr/lib/python3/dist-packages/salt/log/setup.py", line 414, in setup_extended_logging
    providers = salt.loader.log_handlers(opts)
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 686, in log_handlers
    _module_dirs(
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 148, in _module_dirs
    for entry_point in entrypoints.iter_entry_points("salt.loader"):
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 43, in _wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 62, in iter_entry_points
    for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
Usage: salt-call [options] <function> [arguments]

salt-call: error: Error while processing <function LogLevelMixIn.__setup_extended_logging at 0x7f869fe674c0>: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 210, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 887, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/usr/lib/python3/dist-packages/salt/log/setup.py", line 414, in setup_extended_logging
    providers = salt.loader.log_handlers(opts)
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 686, in log_handlers
    _module_dirs(
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 148, in _module_dirs
    for entry_point in entrypoints.iter_entry_points("salt.loader"):
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 43, in _wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 62, in iter_entry_points
    for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'](`url`)
`
```
Any fix to this issue ? 

Thanks.

**Comment by digitalsleuth** [comment]
Hi @faisalusuf , if you run the following, you should be able to rerun the installer without issue.

`sudo python3 -m pip install 'importlib-metadata<5.0.0'`

**Comment by faisalusuf** [comment]
@digitalsleuth Seems it worked. Thanks for your help really appreciate it.

**Comment by digitalsleuth** [comment]
No problem, glad everything worked out!
