### ISSUE TITLE
Error during remnux installation in Ubuntu 20

### ISSUE THREAD

**Issue by joaormv** [REMnux/remnux-cli#12]
Hi remnux team,

 I got this error whe  I executed the command `sudo remnux install --mode=addon` in Ubuntu 20:

```
> remnux-cli@1.3.1.4.ge28588c

Invalid OS or unable to determine Ubuntu version
Error: Invalid OS or unable to determine Ubuntu version
    at validOS (/snapshot/remnux-cli/remnux-cli.js:170:11)
    at run (/snapshot/remnux-cli/remnux-cli.js:674:9)
    at main (/snapshot/remnux-cli/remnux-cli.js:771:11)
    at Object.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:777:1)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:17:47


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```

I couldn't find the /var/cache/remnux directory to check the saltstack.log file as the command output advised me.

Before this I issued these commands:

```
sudo apt-get update && sudo apt-get dist-upgrade
get https://REMnux.org/remnux-cli
mv remnux-cli remnux
chmod +x remnux
sudo mv remnux /usr/local/bin
```

Did I do anything wrong ?

Thank you very much.

**Comment by digitalsleuth** [comment]
@joaormv Unfortunately, Ubuntu 20 is not yet supported. While we are planning to support it, it is still a work-in-progress.

**Comment by joaormv** [comment]
@digitalsleuth thank you for your response.

I'll try another distro.

:+1:

**Comment by digitalsleuth** [comment]
@joaormv We're currently supporting Ubuntu 18.04. You can either use the REMnux CLI, or you can find a VMware or VirtualBox OVA at https://docs.remnux.org
