### ISSUE TITLE
Upgrade Error: Issue with a Release File

### ISSUE THREAD

**Issue by dfirsec** [REMnux/remnux-cli#125]
Attempting to upgrade remnux, I get the following error:

```
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: v2023.9.1

Installing and configuring SaltStack properly ...

Command failed: apt-get update
E: The repository 'https://download.sysdig.com/stable/deb stable-amd64/deb Release' does not have a Release file.

Error: Command failed: apt-get update
E: The repository 'https://download.sysdig.com/stable/deb stable-amd64/deb Release' does not have a Release file.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```
      
This is consistent with what I am seeing in the saltstack.log file: 

```/var/cache/remnux/cli/v2023.13.2                                                                                                                                   
╰─ grep -E -C 5 'result: false' saltstack.log


     __run_num__: 344
    __sls__: remnux.python3-packages.thug
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.thug.remnux-python3-packages-thug-makedir'
    duration: 0.002
    result: false
    start_time: '18:29:20.813996'
  cmd_|-i386-arch_|-dpkg --add-architecture i386 && apt-get update_|-run:
    __id__: i386-arch
    __run_num__: 151
    __sls__: remnux.packages.i386-architecture
--
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.repos.remnux-repos, remnux.config.remnux-config,
      remnux.python3-packages.remnux-python3-packages, remnux.packages.remnux-packages'
    duration: 0.002
    result: false
    start_time: '18:31:26.430142'
  file_|-remnux-config-android-project-creator-permissions_|-/opt/AndroidProjectCreator/library_|-directory:
    __id__: remnux-config-android-project-creator-permissions
    __run_num__: 686
    __sls__: remnux.config.android-project-creator
--
    __sls__: remnux.config.bash-completion
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.thug.remnux-python3-packages-thug-makedir,
      remnux.python3-packages.thug.emnux-python3-packages-thug-conf, remnux.python3-packages.thug.remnux-python3-packages-thug-packages'
    duration: 0.002
    result: false
    start_time: '18:31:05.744526'
  file_|-remnux-config-bash-completion-translate_|-/etc/bash_completion.d/translate_|-managed:
    __id__: remnux-config-bash-completion-translate
    __run_num__: 678
    __sls__: remnux.config.bash-completion
--
    __run_num__: 610
    __sls__: remnux.config.thug
    changes: {}
    comment: 'One or more requisite failed: remnux.config.thug.remnux-config-thug'
    duration: 0.005
    result: false
    start_time: '18:31:03.976518'
  file_|-remnux-config-thug_|-/var/log/thug_|-directory:
    __run_num__: 609
    __sls__: remnux.config.thug
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.thug.remnux-python3-packages-thug-makedir,
      remnux.python3-packages.thug.emnux-python3-packages-thug-conf, remnux.python3-packages.thug.remnux-python3-packages-thug-packages'
    duration: 0.002
    result: false
    start_time: '18:31:03.970888'
  file_|-remnux-config-volatility3-permissions_|-/usr/local/lib/python3.8/dist-packages/volatility3/framework/symbols_|-directory:
    __id__: remnux-config-volatility3-permissions
    __run_num__: 687
    __sls__: remnux.config.volatility3
--
    __run_num__: 364
    __sls__: remnux.python3-packages.droidlysis
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.droidlysis.remnux-python-packages-droidlysis'
    duration: 0.003
    result: false
    start_time: '18:29:34.753261'
  file_|-remnux-python-packages-droidlysis-droidconfig-set2_|-/usr/local/lib/python3.8/dist-packages/droidconfig.py_|-replace:
    __run_num__: 365
    __sls__: remnux.python3-packages.droidlysis
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.droidlysis.remnux-python-packages-droidlysis'
    duration: 0.002
    result: false
    start_time: '18:29:34.754394'
  file_|-remnux-python-packages-droidlysis-droidconfig-set3_|-/usr/local/lib/python3.8/dist-packages/droidconfig.py_|-replace:
    __run_num__: 366
    __sls__: remnux.python3-packages.droidlysis
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.droidlysis.remnux-python-packages-droidlysis'
    duration: 0.001
    result: false
    start_time: '18:29:34.755353'
  file_|-remnux-python-packages-droidlysis-droidconfig-set4_|-/usr/local/lib/python3.8/dist-packages/droidconfig.py_|-replace:
    __run_num__: 367
    __sls__: remnux.python3-packages.droidlysis
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.droidlysis.remnux-python-packages-droidlysis'
    duration: 0.002
    result: false
    start_time: '18:29:34.756295'
  file_|-remnux-python-packages-vipermonkey-symlink_|-/usr/local/bin/vmonkey_|-symlink:
    __id__: remnux-python-packages-vipermonkey-symlink
    __run_num__: 262
    __sls__: remnux.python-packages.vipermonkey
--
    __run_num__: 343
    __sls__: remnux.python3-packages.thug
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.thug.remnux-python3-packages-thug-packages'
    duration: 0.003
    result: false
    start_time: '18:29:20.812786'
  file_|-remnux-python3-packages-volatility-rename-vol_|-/usr/local/bin/vol3_|-rename:
    __id__: remnux-python3-packages-volatility-rename-vol
    __run_num__: 351
    __sls__: remnux.python3-packages.volatility3
--
      \   WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages\nERROR:
      Cannot uninstall python-magic 0.4.24, RECORD file not found. You might be able
      to recover from this via: 'pip install --force-reinstall --no-deps python-magic==0.4.24'."
    duration: 2066.107
    name: droidlysis
    result: false
    start_time: '18:29:32.685082'
  pip_|-remnux-python-packages-m2crypto_|-m2crypto_|-installed:
    __id__: remnux-python-packages-m2crypto
    __run_num__: 266
    __sls__: remnux.python-packages.m2crypto
--
      \   WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages\nERROR:
      Cannot uninstall python-magic 0.4.24, RECORD file not found. You might be able
      to recover from this via: 'pip install --force-reinstall --no-deps python-magic==0.4.24'."
    duration: 2355.16
    name: thug
    result: false
    start_time: '18:29:18.452528'
  pip_|-remnux-python3-packages-time-decode_|-time-decode_|-installed:
    __id__: remnux-python3-packages-time-decode
    __run_num__: 356
    __sls__: remnux.python3-packages.time-decode
--
    __run_num__: 130
    __sls__: remnux.packages.sysdig
    changes: {}
    comment: 'One or more requisite failed: remnux.repos.draios.draios'
    duration: 0.002
    result: false
    start_time: '18:28:00.583966'
  pkg_|-remnux-tools-detect-it-easy-install_|-remnux-tools-detect-it-easy-install_|-installed:
    __id__: remnux-tools-detect-it-easy-install
    __run_num__: 777
    __sls__: remnux.tools.detect-it-easy
--
      https://download.sysdig.com/stable/deb stable-amd64/'': E: The repository ''https://download.sysdig.com/stable/deb
      stable-amd64/deb Release'' does not have a Release file.'
    duration: 4365.561
    name: deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb
      stable-amd64/
    result: false
    
    ...
```

**Comment by digitalsleuth** [comment]
Hi @dfirsec , can you provide the following:

- a copy of your saltstack.log file
- the contents of your `/etc/apt/sources.list.d/draios.list` file
- the output of `cat /etc/os-release` and `lsb_release -a`

Thanks!

**Comment by dfirsec** [comment]
Please see below and attached.  

Thanks!

```
╰─ cat /etc/apt/sources.list.d/draios.list
           
deb https://download.sysdig.com/stable/deb stable-$(ARCH)/
deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb stable-amd64/
```

```
╰─ cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```


```
╰─ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

```
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11147812/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @dfirsec , it looks like you have an extra line in your draios.list file which is causing the issue. Can you remove the line with the `$(ARCH)` in it?

This file should only contain:
```bash
deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb stable-amd64/
```

Once you fix that, run `sudo apt-get update && sudo apt-get upgrade -y` and you can try your install again.

**Comment by dfirsec** [comment]
@digitalsleuth I made the change and rebooted.  However, re-running `sudo remnux upgrade` returned the following at the very end:
```
Update returned exit code not zero
Error: Update ret
[saltstack.log](https://git
[saltstack_2.log](https://github.com/REMnux/remnux-cli/files/11148198/saltstack_2.log)
hub.com/REMnux/remnux-cli/files/11148193/saltstack.log)
urned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildPr
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11148187/saltstack.log)
ocess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.
```

I'm not experiencing any connectivity/latency issues, that I am aware of.  In any case, I'll try again later and see if successful. If need, attached is the latest saltstack.log file  for your review.

Thanks again.

[saltstack_2.log](https://github.com/REMnux/remnux-cli/files/11148202/saltstack_2.log)

**Comment by digitalsleuth** [comment]
So it looks like there were only two packages now that had errors, thug and droidlysis, both centered around an issue with python-magic. Can you run the following and provide the results:

`sudo apt search python-magic`

If either or both of the python-magic packages there show as installed, then that's where the problem lies. Both thug and droidlysis are trying to install the latest python-magic but it's showing as installed, but can't be uninstalled by python.

The quick solution to this would be:
`sudo apt remove python-magic -y`

then

`sudo python3 -m pip install python-magic `
This should fix the conflict, and allow you to try the installation again.

**Comment by dfirsec** [comment]
Here's the output for each:

1.  `sudo apt search python-magic`
```
Sorting... Done
Full Text Search... Done
python-magic/focal,focal,focal,focal,now 2:0.4.15-3 all [installed]
  python2 interface to the libmagic file type identification library

python3-magic/focal,focal,now 2:0.4.15-3 all [installed]
  python3 interface to the libmagic file type identification library
```

2. `sudo apt remove python-magic -y`
```
╰─ sudo apt remove python-magic -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  python-magic
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
After this operation, 43.0 kB disk space will be freed.
(Reading database ... 393302 files and directories currently installed.)
Removing python-magic (2:0.4.15-3) ...
```

3. `sudo python3 -m pip install python-magic`
```
╰─ sudo python3 -m pip install python-magic 
Requirement already satisfied: python-magic in /usr/local/lib/python3.8/dist-packages (0.4.24)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/python_magic-0.4.24.dist-info/METADATA'
```

**Comment by dfirsec** [comment]
Forgot to mention that I also get a 404 error for `download.sysdig.com` when updating....

```
Hit:13 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease
Ign:14 https://download.sysdig.com/stable/deb stable-amd64/deb InRelease
Hit:15 http://www.inetsim.org/debian binary/ InRelease
Get:16 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Err:17 https://download.sysdig.com/stable/deb stable-amd64/deb Release
  404  Not Found [IP: 18.160.213.34 443]
Hit:18 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease
Hit:19 http://ppa.launchpad.net/remnux/stable/ubuntu focal InRelease
Hit:20 http://ppa.launchpad.net/sift/stable/ubuntu focal InRelease
Hit:21 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu focal InRelease
```

**Comment by digitalsleuth** [comment]
For the python-magic, can you run `sudo python3 -m pip install --upgrade python-magic` and see if that resolves the OSError?
As for the sysdig, I'm seeing that as well. Looks like they're having some issues with their repo.

I'll poke around and see if I can get some more info.

**Comment by digitalsleuth** [comment]
Issue raised at [draios/sysdig/issues/1985](https://github.com/draios/sysdig/issues/1985). I'll let you know when I know more!

**Comment by dfirsec** [comment]
> For the python-magic, can you run `sudo python3 -m pip install --upgrade python-magic` and see if that resolves the OSError? As for the sysdig, I'm seeing that as well. Looks like they're having some issues with their repo.
> 
> I'll poke around and see if I can get some more info.

```
sudo python3 -m pip install --upgrade python-magic
Requirement already satisfied: python-magic in /usr/local/lib/python3.8/dist-packages (0.4.24)
Collecting python-magic
  Downloading python_magic-0.4.27-py2.py3-none-any.whl (13 kB)
WARNING: Error parsing requirements for python-magic: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/python_magic-0.4.24.dist-info/METADATA'
Installing collected packages: python-magic
  Attempting uninstall: python-magic
    WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages
    Found existing installation: python-magic 0.4.24
ERROR: Cannot uninstall python-magic 0.4.24, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps python-magic==0.4.24'.
```

**Comment by digitalsleuth** [comment]
Try running the recommended command at the bottom:
`sudo python3 -m pip install --force-reinstall --no-deps python-magic==0.4.24`

**Comment by dfirsec** [comment]
> Try running the recommended command at the bottom: `sudo python3 -m pip install --force-reinstall --no-deps python-magic==0.4.24`

Yep, tried that as well and got the same error.  So, I ran `pip show python-magic` to find the appropriate directory and deleted it: `sudo rm -rf /usr/local/lib/python3.8/dist-packages/python_magic-0.4.24.dist-info/`.  

I then ran `sudo python3 -m pip install --upgrade python-magic` and was able to successfully install it.

```
> pip show python-magic           

Name: python-magic
Version: 0.4.27
Summary: File type identification using libmagic
Home-page: http://github.com/ahupp/python-magic
Author: Adam Hupp
Author-email: adam@hupp.org
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: peframe-ds, thug, droidlysis
```

Re-ran remnux upgrade and of course I get this error: 😄 

```
Installing and configuring SaltStack properly ...

Command failed: apt-get update
E: The repository 'https://download.sysdig.com/stable/deb stable-amd64/deb Release' does not have a Release file.

Error: Command failed: apt-get update
E: The repository 'https://download.sysdig.com/stable/deb stable-amd64/deb Release' does not have a Release file.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

**Comment by digitalsleuth** [comment]
@dfirsec Out of curiosity, are you attempting to run the install from an AWS instance?

**Comment by dfirsec** [comment]
> @dfirsec Out of curiosity, are you attempting to run the install from an AWS instance?

Nope, using Hyper-V on a home machine.

**Comment by digitalsleuth** [comment]
@dfirsec , could you provide an nslookup for both `download.sysdig.com` and `download.draios.com`?

**Comment by dfirsec** [comment]
> @dfirsec , could you provide an nslookup for both `download.sysdig.com` and `download.draios.com`?

Here you go...

```
╰─ nslookup download.sysdig.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	download.sysdig.com
Address: 18.160.213.34
Name:	download.sysdig.com
Address: 18.160.213.35
Name:	download.sysdig.com
Address: 18.160.213.7
Name:	download.sysdig.com
Address: 18.160.213.55
```

```
╰─ nslookup download.draios.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
download.draios.com	canonical name = download.draios.com.s3-website-us-east-1.amazonaws.com.
download.draios.com.s3-website-us-east-1.amazonaws.com	canonical name = s3-website.us-east-1.amazonaws.com.
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.217.168.109
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.217.121.157
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.216.44.29
Name:	s3-website.us-east-1.amazonaws.com
Address: 54.231.163.93
Name:	s3-website.us-east-1.amazonaws.com
Address: 54.231.162.13
Name:	s3-website.us-east-1.amazonaws.com
Address: 54.231.140.85
Name:	s3-website.us-east-1.amazonaws.com
Address: 54.231.134.37
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.217.103.83
```

**Comment by therealbobo** [comment]
It's very strange: even if I use the IP (modifying the /etc/hosts file) that wasn't working I can reach the repo and install the package. Could you please verify if now it's working? 🤔

**Comment by digitalsleuth** [comment]
It seems to be working for me. @dfirsec , how about you?

**Comment by dfirsec** [comment]
Still seeing an issue on my side when initiating an update....

```
Hit:14 http://www.inetsim.org/debian binary/ InRelease                                                                                                   
Get:15 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                                                                
Err:16 https://download.sysdig.com/stable/deb stable-amd64/deb Release          
  404  Not Found [IP: 18.160.213.55 443]
Hit:17 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease            
Hit:18 http://ppa.launchpad.net/sift/stable/ubuntu focal InRelease                     
Hit:19 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu focal InRelease
Get:20 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease [18.0 kB]
Get:21 http://ppa.launchpad.net/remnux/stable/ubuntu focal InRelease [18.1 kB]
Reading package lists... Done                        
E: The repository 'https://download.sysdig.com/stable/deb stable-amd64/deb Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Release file for http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease is not valid yet (invalid for another 56min 49s). Updates for this repository will not be applied.
E: Release file for http://us.archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease is not valid yet (invalid for another 58min 9s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/focal-security/InRelease is not valid yet (invalid for another 56min 49s). Updates for this repository will not be applied.
E: Release file for http://ppa.launchpad.net/gift/stable/ubuntu/dists/focal/InRelease is not valid yet (invalid for another 1h 7min 37s). Updates for this repository will not be applied.
E: Release file for http://ppa.launchpad.net/remnux/stable/ubuntu/dists/focal/InRelease is not valid yet (invalid for another 1h 7min 46s). Updates for this repository will not be applied.
```

**Comment by digitalsleuth** [comment]
Well I think I see an issue. Check your date and time settings first, it looks like they're out of sync. Please update that and try again.

**Comment by dfirsec** [comment]
Sorry if I'm misunderstanding your suggestion, do you mean sync as in this?  
```
╰─ timedatectl                    

               Local time: Tue 2023-04-04 19:25:59 UTC
           Universal time: Tue 2023-04-04 19:25:59 UTC
                 RTC time: Tue 2023-04-04 19:25:59    
                Time zone: UTC (UTC, +0000)           
System clock synchronized: yes                        
              NTP service: active                     
          RTC in local TZ: no   
```

**Comment by digitalsleuth** [comment]
Yes, looks good. Typically when an apt error like `is not valid yet (invalid for another 1h 7min 46s)`, it means that your system's time is incorrect, and likely set too far in the past or in the future. Yours looks good right now. Can you try `sudo apt-get update` again?

**Comment by digitalsleuth** [comment]
This could all be a part of the [Cloudflare maintenance](https://www.cloudflarestatus.com/) that's been going on all day today. I'll check again in a few hours to see if this has been resolved.

**Comment by dfirsec** [comment]
Ok, I got it now.  Somehow these other entries got put back in... 🤷🏼‍♂️ 

```
─ cat /etc/apt/sources.list.d/draios.list
deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb stable-amd64/
deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb stable-amd64/deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb stable-amd64/% 
```

Removed the other entries so that I only have:
`deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb stable-amd64/`
...and all is working now. 👍🏼 

```
╰─ sudo apt-get update                          
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                                                                                    
Hit:3 http://deb.nodesource.com/node_14.x focal InRelease                                                                                                                                                 
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                                                                         
Hit:5 http://packages.microsoft.com/repos/vscode stable InRelease                                                                                                                                         
Hit:6 http://archive.ubuntu.com/ubuntu focal-security InRelease                                                                                                                                           
Hit:7 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                                                                                       
Hit:8 https://download.mono-project.com/repo/ubuntu stable-focal InRelease                                                                                                                                
Hit:9 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease                                                                                                                                    
Hit:10 https://download.sysdig.com/stable/deb stable-amd64/ InRelease                                                                                                                    
Hit:11 http://security.ubuntu.com/ubuntu focal-security InRelease                                                                                                  
Hit:12 https://download.docker.com/linux/ubuntu focal InRelease                                                                              
Hit:13 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease                                         
Hit:14 http://www.inetsim.org/debian binary/ InRelease              
Hit:15 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease
Hit:16 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease
Hit:17 http://ppa.launchpad.net/remnux/stable/ubuntu focal InRelease
Hit:18 http://ppa.launchpad.net/sift/stable/ubuntu focal InRelease
Hit:19 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu focal InRelease
Reading package lists... Done    
```

```
>> Running: /etc/remnux-version

>> COMPLETED SUCCESSFULLY! Success: 785, Failure: 0


>> Please reboot to make sure all settings go into effect.
```

Thanks for your help!
