### ISSUE TITLE
iossue with remnux upgrade on newly downloaded VM

### ISSUE THREAD

**Issue by horserunning** [REMnux/remnux-cli#127]
hello, 

I downloaded the VM remnux-v7-focal.ova and verified that the checksum is correct. 
I imported the ova into VMWare fusion and I didn't have any issues. 

When I run _remnux upgrade_ the process stops at the end with: 

```
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
```

I tried the _remnux upgrade_ multiple times and I also tried the _remnux update_, but I receive the same error. 

I checked in the file /var/cache/remnux/cli/v2023.15.1/saltstack.log and the first occurrence of _result: false_ shows: 

```
start_time: '12:22:07.381141'
  archive_|-remnux-mitmproxy-archive_|-/usr/local/bin/_|-extracted:
    __run_num__: 321
    __sls__: remnux.python3-packages.mitmproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.mitmproxy.remnux-mitmproxy-source'
    duration: 0.009
    result: false
```
I checked the my firewall is not blocking the connection, and it doesn't. 
It seems the dependencies are all complaining for this file. 
I attached the saltstack.log in case it can be relevant. 

How can I move on and get the VM updated? 

Thanks,  
Alex

[saltstack.log.zip](https://github.com/REMnux/remnux-cli/files/11214531/saltstack.log.zip)

**Comment by digitalsleuth** [comment]
Hi @horserunning , can you provide the output of the following command:
```bash
cat /etc/apt/sources.list.d/vscode.list
```

**Comment by horserunning** [comment]
Sure: 

```
remnux@remnux:~$ cat /etc/apt/sources.list.d/vscode.list
deb [arch=amd64 signed-by=/usr/share/keyrings/MICROSOFT.asc] http://packages.microsoft.com/repos/vscode stable main
```

**Comment by digitalsleuth** [comment]
Hi @horserunning , can you also provide the content of the microsoft.list file as well, and the output of the following:
`sudo apt-get update`

**Comment by horserunning** [comment]
Sure: 

The content of the file: 
```
remnux@remnux:/etc/apt/sources.list.d$ cat microsoft.list  
deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main

```
Output of the update command

```
remnux@remnux:/etc/apt/sources.list.d$ sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:2 https://download.sysdig.com/stable/deb stable-amd64/ InRelease                                                                                     
Hit:3 https://download.docker.com/linux/ubuntu focal InRelease                                                                                           
Get:4 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease [2,125 B]                                                                  
Get:5 http://packages.microsoft.com/repos/vscode stable InRelease [2,413 B]                                                                              
Hit:6 http://us.archive.ubuntu.com/ubuntu focal InRelease                                                                                                
Get:7 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease [18.0 kB]                                                                              
Hit:8 https://download.mono-project.com/repo/ubuntu stable-focal InRelease                                                                               
Hit:9 http://www.inetsim.org/debian binary/ InRelease                                                                                                    
Get:10 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                                                              
Get:11 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [3,611 B]                                 
Hit:12 http://deb.nodesource.com/node_14.x focal InRelease                                                                      
Get:13 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]                    
Hit:14 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease                  
Get:15 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [165 kB]
Get:16 http://ppa.launchpad.net/remnux/stable/ubuntu focal InRelease [18.1 kB]
Hit:17 http://ppa.launchpad.net/sift/stable/ubuntu focal InRelease                   
Hit:18 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu focal InRelease
Get:19 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,085 kB]
Get:20 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages [575 kB]
Get:21 http://us.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [807 kB]
Get:22 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [12.5 kB]
Get:23 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [821 kB]  
Get:24 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2,469 kB]   
Get:25 http://us.archive.ubuntu.com/ubuntu focal-updates/main Translation-en [421 kB]
Get:26 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [16.4 kB]
Get:27 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,047 kB]
Get:28 http://us.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [722 kB]
Fetched 9,521 kB in 4s (2,252 kB/s)                       
Reading package lists... Done
```

**Comment by digitalsleuth** [comment]
Hi @horserunning , it looks like everything seems to be fine. You should be able to try your upgrade again without issue.

For what it's worth, the error you gave [here](https://github.com/REMnux/remnux-cli/issues/127#issue-1665019995) does not match what's in the log you provided in the same comment. This is what it shows in your attached log for the mitmproxy archive, so possibly you provided the wrong log file?
```bash
 archive_|-remnux-mitmproxy-archive_|-/usr/local/bin/_|-extracted:
    __id__: remnux-mitmproxy-archive
    __run_num__: 322
    __sls__: remnux.python3-packages.mitmproxy
    changes: {}
    comment: All files in archive are already present
    duration: 360.519
    name: /usr/local/bin/
    result: true
    start_time: '13:59:23.165953'
```

**Comment by horserunning** [comment]
Thank you for your reply, and I apologize for the delayed answer. 

Regarding the log file, I have two directories containing the saltstack.log, and the one on the 2023.15.1 directory is the one that gets updated. 

Anyway, magically, the remnux upgrade worked fine today, and I have no idea why because I didn't change anything on my side or in my network. 

Thank you for helping me with this issue.
