### ISSUE TITLE
remnux upgrade (issue)

### ISSUE THREAD

**Issue by wabass** [REMnux/remnux-cli#128]
I guess it needs an update.
Hence, Im now using the OVA version but when I upgrade it ends up like this.
Im using Focal Version.

![image](https://user-images.githubusercontent.com/109649776/231729037-cb4785d9-8c30-4fae-bc8a-08871a9f8287.png)

**Comment by digitalsleuth** [comment]
Hi @wabass , Can you send us a copy of your saltstack.log file so we can assist? Thanks!

**Comment by wabass** [comment]
Sure
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11223475/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @wabass , it looks like during the install you had an internet connectivity issue which prevented two Python packages from installing:
```bash
socket.timeout: The read operation timed out
--snip--
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

If you try the install/upgrade it should work fine, provided you have a stable internet connection during the install/upgrade.

**Comment by wabass** [comment]
Still the same, I deleted the cache and this is the new logs.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/11228628/saltstack.log)



>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by wabass** [comment]
`remnux@remnux:~/Desktop$ sudo apt-get update
Err:1 http://us/archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'us'
Hit:2 http://packages.microsoft.com/repos/vscode stable InRelease                                                       
Hit:3 https://download.docker.com/linux/ubuntu focal InRelease                                                          
Hit:4 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease                                                  
Hit:5 https://download.mono-project.com/repo/ubuntu stable-focal InRelease                                              
Hit:6 https://deb.nodesource.com/node_14.x focal InRelease                                                              
Hit:7 http://us.archive.ubuntu.com/ubuntu focal InRelease                                                               
Hit:8 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease                                                       
Ign:9 http://www.inetsim.org/debian binary/deb InRelease                                                                
Hit:10 http://download.draios.com/stable/deb stable-amd64/ InRelease                                                    
Hit:11 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease                                                      
Hit:12 http://www.inetsim.org/debian binary/ InRelease                                                                  
Hit:13 http://ppa.launchpadcontent.net/openjdk-r/ppa/ubuntu focal InRelease                                             
Hit:14 http://ppa.launchpad.net/remnux/stable/ubuntu focal InRelease                                                    
Get:15 http://us.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                            
Err:16 http://www.inetsim.org/debian binary/deb Release                                                                 
  404  Not Found [IP: 85.214.152.164 80]
Hit:17 https://repo.saltproject.io/py3/ubuntu/20.04/arm64/3004 focal InRelease                                          
Ign:18 https://download.sysdig.com/stable/deb stable-amd64/deb InRelease                                                
Hit:19 http://ppa.launchpad.net/sift/stable/ubuntu focal InRelease                                                      
Hit:20 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu focal InRelease                                             
Get:21 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]                                           
Err:22 https://download.sysdig.com/stable/deb stable-amd64/deb Release                                                  
  404  Not Found [IP: 13.224.167.98 443]
Get:23 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease [2,125 B]                                
Err:24 https://us.archive.canonical.com/ubuntu focal InRelease                                                          
  Could not connect to us.archive.canonical.com:443 (185.125.189.10). - connect (111: Connection refused)
Reading package lists... Done                               
E: The repository 'http://www.inetsim.org/debian binary/deb Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://download.sysdig.com/stable/deb stable-amd64/deb Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by wabass** [comment]
```
remnux@remnux:/var/cache/remnux/cli$ sudo apt update
Err:1 http://us/archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'us'
Hit:2 http://packages.microsoft.com/repos/vscode stable InRelease                      
Hit:3 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease                 
Hit:4 https://download.docker.com/linux/ubuntu focal InRelease                         
Hit:5 https://download.mono-project.com/repo/ubuntu stable-focal InRelease             
Hit:6 https://deb.nodesource.com/node_14.x focal InRelease                             
Get:7 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease [18.0 kB]            
Hit:8 http://download.draios.com/stable/deb stable-amd64/ InRelease                    
Hit:9 http://ppa.launchpadcontent.net/openjdk-r/ppa/ubuntu focal InRelease             
Hit:10 https://repo.saltproject.io/py3/ubuntu/20.04/arm64/3004 focal InRelease         
Ign:11 http://www.inetsim.org/debian binary/deb InRelease                              
Hit:12 http://us.archive.ubuntu.com/ubuntu focal InRelease                             
Get:13 http://ppa.launchpad.net/remnux/stable/ubuntu focal InRelease [18.1 kB]         
Ign:14 https://download.sysdig.com/stable/deb stable-amd64/deb InRelease               
Hit:15 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease                     
Hit:16 http://www.inetsim.org/debian binary/ InRelease                                 
Get:17 http://us.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]           
Err:18 http://www.inetsim.org/debian binary/deb Release                                
  404  Not Found [IP: 85.214.152.164 80]
Hit:19 http://ppa.launchpad.net/sift/stable/ubuntu focal InRelease                     
Get:20 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease [2,125 B]
Err:21 https://download.sysdig.com/stable/deb stable-amd64/deb Release                 
  404  Not Found [IP: 13.224.167.30 443]
Hit:22 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu focal InRelease            
Get:23 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]          
Err:24 https://us.archive.canonical.com/ubuntu focal InRelease                         
  Could not connect to us.archive.canonical.com:443 (185.125.189.10). - connect (111: Connection refused)
Reading package lists... Done                               
E: The repository 'http://www.inetsim.org/debian binary/deb Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://download.sysdig.com/stable/deb stable-amd64/deb Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
remnux@remnux:/var/cache/remnux/cli$ 

```

**Comment by digitalsleuth** [comment]
Can you take a look at the following files from `/etc/apt/sources.list.d/` and provide the content:
```bash
draios.list
inetsim.list
```
And the contents of the `/etc/apt/sources.list` file.

It appears that these list files may have incorrect entries in them, which appears to be causing some of the issues you're having.
The draios list should be one line:
```bash
deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb stable-amd64/
```
The inetsim.list should be one line as well:
```bash
deb [signed-by=/usr/share/keyrings/INETSIM-GPG-KEY.asc] http://www.inetsim.org/debian/ binary/
```

And the line in your `sources.list` file which has `backports` looks like it might have a typo. From your log it shows:
```bash
http://us/archive.ubuntu.com/ubuntu focal-backports
```
Notice the misplaced forward-slash. But instead it should be 
```bash
http://us.archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
```

**Comment by wabass** [comment]
Fixed it. And re-build it.

```
remnux@remnux:~$ sudo apt update && sudo apt upgrade -y
Get:1 http://packages.microsoft.com/repos/vscode stable InRelease [2,413 B]
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                                                                                                
Get:3 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease [18.0 kB]                                                                                                              
Hit:4 http://us.archive.ubuntu.com/ubuntu focal InRelease                                                                                                                                
Get:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [3,611 B]                                                                                                         
Get:6 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                                                                                               
Hit:7 https://download.mono-project.com/repo/ubuntu stable-focal InRelease                                                                                                               
Get:8 https://download.docker.com/linux/ubuntu focal InRelease [57.7 kB]                                                                                                                 
Hit:9 https://deb.nodesource.com/node_14.x focal InRelease                                                                                                                               
Hit:10 http://ppa.launchpadcontent.net/openjdk-r/ppa/ubuntu focal InRelease                                                                                                              
Get:11 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [165 kB]                                                                                                    
Hit:12 http://www.inetsim.org/debian binary/ InRelease                                                                                                                                   
Get:13 http://ppa.launchpad.net/remnux/stable/ubuntu focal InRelease [18.1 kB]                                                                                                           
Hit:14 https://download.sysdig.com/stable/deb stable-amd64/ InRelease                                                                                                              
Hit:15 https://repo.saltproject.io/py3/ubuntu/20.04/arm64/3004 focal InRelease                                                                     
Get:16 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease [2,125 B]                                                     
Get:17 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]     
Hit:18 http://ppa.launchpad.net/sift/stable/ubuntu focal InRelease
Hit:19 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu focal InRelease            
Get:20 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2,469 kB]
Get:21 http://us.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [807 kB]                                                                                                     
Get:22 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,047 kB]                                                                                              
Get:23 http://us.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [722 kB]                                                                                                 
Fetched 5,649 kB in 14s (414 kB/s)                                                                                                                                                       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
```

Even if I did rebuild it still got the error.

```
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

```
Check this one.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/11241380/saltstack.log)

**Comment by wabass** [comment]
For Ubuntu 20.04 Focal.

```
bassemer@ubuntu:/etc/apt$ sudo remnux install
[sudo] password for bassemer: 
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: notinstalled

> downloading v2023.15.1
>> downloading remnux-salt-states-v2023.15.1.tar.gz.asc
>> downloading remnux-salt-states-v2023.15.1.tar.gz.sha256
>> downloading remnux-salt-states-v2023.15.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2023.15.1.tar.gz
> validating file remnux-salt-states-v2023.15.1.tar.gz
> validating signature for remnux-salt-states-v2023.15.1.tar.gz.sha256
> extracting update remnux-salt-states-v2023.15.1.tar.gz
> no previous REMnux version found; performing a new 'dedicated' installation.
> upgrading/updating to v2023.15.1
>> Log file: /var/cache/remnux/cli/v2023.15.1/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues


bassemer@ubuntu:/etc/apt$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

```
saltstack.log printed

```
bassemer@ubuntu:/etc/apt$ cat /var/cache/remnux/cli/v2023.15.1/saltstack.log 
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ubuntu
[DEBUG   ] Using importlib_metadata to load entry points
[ERROR   ] 'EntryPoints' object has no attribute 'items'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 210, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 887, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/usr/lib/python3/dist-packages/salt/log/setup.py", line 414, in setup_extended_logging
    providers = salt.loader.log_handlers(opts)
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 686, in log_handlers
    _module_dirs(
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 148, in _module_dirs
    for entry_point in entrypoints.iter_entry_points("salt.loader"):
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 43, in _wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 62, in iter_entry_points
    for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
Usage: salt-call [options] <function> [arguments]

salt-call: error: Error while processing <function LogLevelMixIn.__setup_extended_logging at 0x7fb1e7e284c0>: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 210, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 887, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/usr/lib/python3/dist-packages/salt/log/setup.py", line 414, in setup_extended_logging
    providers = salt.loader.log_handlers(opts)
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 686, in log_handlers
    _module_dirs(
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 148, in _module_dirs
    for entry_point in entrypoints.iter_entry_points("salt.loader"):
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 43, in _wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 62, in iter_entry_points
    for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'

```

**Comment by wabass** [comment]
Im thinking of installing all the remnux tools manually now.

**Comment by konradx** [comment]
@wabass I had exactly the same issue.
If you look into your saltstack.log file you'll find:
`
  file_|-remnux-mitmproxy-source_|-/usr/local/src/remnux/files/mitmproxy-6.0.2-linux.tar.gz_|-managed:
    __id__: remnux-mitmproxy-source
    __run_num__: 321
    __sls__: remnux.python3-packages.mitmproxy
    changes: {}
    comment: 'Failed to cache http://snapshots.mitmproxy.org/6.0.2/mitmproxy-6.0.2-linux.tar.gz:
      Error: HTTP 503: Service Unavailable reading /6.0.2/mitmproxy-6.0.2-linux.tar.gz'
    duration: 414.926
    name: /usr/local/src/remnux/files/mitmproxy-6.0.2-linux.tar.gz
    result: false
    start_time: '01:49:56.722668'
`

Maybe your firewall is blocking this url?

**Comment by digitalsleuth** [comment]
Hi @wabass , sorry for not getting back to you sooner. Your last error message can be fixed by running:
`sudo python3 -m pip install "importlib-metadata<5.0.0"`

This is a Saltstack issue with a dependency, but the command above should fix it.

**Comment by wabass** [comment]
> Hi @wabass , sorry for not getting back to you sooner. Your last error message can be fixed by running: `sudo python3 -m pip install "importlib-metadata<5.0.0"`
> 
> This is a Saltstack issue with a dependency, but the command above should fix it.

Hello bud,
This is the new error now.

```
remnux@remnux:~$ sudo python3 -m pip install "importlib-metadata<5.0.0"
Requirement already satisfied: importlib-metadata<5.0.0 in /usr/local/lib/python3.8/dist-packages (4.12.0)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata<5.0.0) (1.0.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1673, in print
    extend(render(renderable, render_options))
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1305, in render
    for render_output in iter_render:
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/segment.py", line 249, in split_lines
    for segment in segments:
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1283, in render
    renderable = rich_cast(renderable)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'
Call stack:
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py", line 190, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py", line 236, in pip_self_version_check
    logger.warning("[present-rich] %s", upgrade_prompt)
  File "/usr/lib/python3.8/logging/__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.2.2', new='23.1'),)

```

**Comment by wabass** [comment]
I managed somehow to install all the tools to Ubuntu 20.04 Focal. Using the native Remnux install "sudo remnux install". 
Even if it has errors.

For: > sudo remnux install returned like this.
```
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

```
For:> sudo remnux upgrade
```
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

```

Even I have these errors. I managed to install all the tools including the wallpaper of remnux.
Which I think im okay for this.

**Comment by wabass** [comment]
I recon, I will maybe try to do it using "cast" repo. (https://github.com/ekristen/cast)
This way I could use 22.04 Jammy. This is a good process to evolve. What you think @digitalsleuth ?

**Comment by digitalsleuth** [comment]
Hi @wabass , before you try Cast, can you upload your most recent saltstack.log file? We want to ensure that there are no further issues which will prevent installation of tools, no matter the installer.

As for Cast, since REMnux does not yet support 22.04 Jammy, the installation of REMnux will not work. This is the same for the remnux-cli as well.

We are currently in the testing phase for Jammy, and hope to complete it soon.

**Comment by wabass** [comment]
@digitalsleuth 
This is from the remnux itself.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11316186/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @wabass , After reviewing your saltstack.log file, it looks like there were two errors. One was a timeout downloading the mitmproxy archive, and the other was a configuration issue with the nodejs repo.

If you're still experiencing this issue, can you provide the content of your `/etc/apt/sources.list.d/nodesource.list` file?
