### ISSUE TITLE
remnux addon issue

### ISSUE THREAD

**Issue by jw4n6** [REMnux/remnux-cli#129]
another issue. Looks to be related to nodejs and vscode.

```console
 $ sudo remnux install --mode=addon
> > remnux-cli@1.3.4.2.g87c65ef
> > remnux-version: notinstalled

....................................................................................

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```

```console
$ grep -i -C 5 'result: false' /var/cache/remnux/cli/v2023.15.1/saltstack.log
    __run_num__: 784
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.repos.remnux-repos, remnux.packages.remnux-packages'
    duration: 0.002
    result: false
    start_time: '03:42:16.648905'
  file_|-remnux-config-android-project-creator-permissions_|-/opt/AndroidProjectCreator/library_|-directory:
    __id__: remnux-config-android-project-creator-permissions
    __run_num__: 686
    __sls__: remnux.config.android-project-creator
--
    comment: "Problem encountered installing package(s). Additional info follows:\n\nerrors:\n
      \   - Running scope as unit: run-r0b0fa70a3185483996ae881b9b88f04c.scope\n      E:
      Unable to locate package code"
    duration: 1351.672
    name: code
    result: false
    start_time: '03:37:31.218890'
  pkg_|-default-jdk_|-default-jdk_|-installed:
    __id__: default-jdk
    __run_num__: 766
    __sls__: remnux.packages.default-jdk
--
    __sls__: remnux.repos.microsoft-vscode
    changes: {}
    comment: 'One or more requisite failed: remnux.repos.nodejs.nodejs-repo-cleanup,
      remnux.repos.nodejs.nodejs-repo'
    duration: 0.002
    result: false
    start_time: '03:37:23.397469'
  ? pkgrepo_|-microsoft_|-deb [arch=amd64 signed-by=/usr/share/keyrings/MICROSOFT.asc]
    https://packages.microsoft.com/ubuntu/20.04/prod focal main_|-managed
  : __id__: microsoft
    __run_num__: 22
--
    changes: {}
    comment: Repo deb https://deb.nodesource.com/node_14.x focal main doesn't exist
      in the sources.list(s)
    duration: 78.091
    name: deb https://deb.nodesource.com/node_14.x focal main
    result: false
    start_time: '03:37:23.314938'
  ? pkgrepo_|-nodejs-repo_|-deb [signed-by=/usr/share/keyrings/NODESOURCE-GPG.KEY]
    http://deb.nodesource.com/node_14.x focal main_|-managed
  : __run_num__: 26
    __sls__: remnux.repos.nodejs
    changes: {}
    comment: 'One or more requisite failed: remnux.repos.nodejs.nodejs-repo-cleanup'
    duration: 0.002
    result: false
    start_time: '03:37:23.395777'
  pkgrepo_|-openjdk-repo_|-openjdk-repo_|-managed:
    __id__: openjdk-repo
    __run_num__: 11
    __sls__: remnux.repos.openjdk
--
    __run_num__: 240
    __sls__: remnux.packages
    changes: {}
    comment: 'One or more requisite failed: remnux.packages.vscode.code'
    duration: 0.006
    result: false
    start_time: '03:37:39.084562'
  test_|-remnux-perl-packages_|-remnux-perl-packages_|-nop:
    __id__: remnux-perl-packages
    __run_num__: 783
    __sls__: remnux.perl-packages
--
    __sls__: remnux.repos
    changes: {}
    comment: 'One or more requisite failed: remnux.repos.nodejs.nodejs-repo-cleanup,
      remnux.repos.nodejs.nodejs-repo, remnux.repos.microsoft-vscode.microsoft-vscode'
    duration: 0.004
    result: false
    start_time: '03:37:23.407727'
  test_|-remnux-rubygems_|-remnux-rubygems_|-nop:
    __id__: remnux-rubygems
    __run_num__: 423
    __sls__: remnux.rubygems
```

**Comment by digitalsleuth** [comment]
Hi @wahlgren , would you mind uploading your saltstack.log file so we can review it to find the cause of the errors? Additionally, since you seem to be having issues with code and nodejs, can you also provide the contents of their `.list` files in the `/etc/apt/sources.list.d` directory? Thanks!

**Comment by jw4n6** [comment]
@digitalsleuth , attached is the saltstack.log and listed below is the content of the two repos I could identify belonging to code and node.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/11307456/saltstack.log)

```console
$ cat /etc/apt/sources.list.d/microsoft.list 
deb [arch=amd64 signed-by=/usr/share/keyrings/MICROSOFT.asc] https://packages.microsoft.com/ubuntu/20.04/prod focal main

$ cat /etc/apt/sources.list.d/nodesource.list
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x focal main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x focal main
```

**Comment by digitalsleuth** [comment]
Hi @wahlgren , the error you're running into with Node is because you have a `deb-src` line in your .list file which shouldn't be there. If you remove the second line from your `nodesource.list` file (which starts with `deb-src`, then you shouldn't have any issues with node. 

Because VS Code requires nodejs, that's also the reason you had the `code` error. If you run a `sudo apt-get update && sudo apt-get install code nodejs -y` then both of these will be installed and you should be good to go. Everything else appears to have installed properly.

Cheers!

**Comment by jw4n6** [comment]
@digitalsleuth thank you, however this did not resolve the issue. After some troubleshooting, the best approach seemed to have been to uninstall nodejs, autoremove apt packages, reboot, remove the two repositories and run the remnux installer again which this time finished without errors.

Cheers!

**Comment by digitalsleuth** [comment]
@wahlgren I'm sorry this approach didn't resolve for you, however I am glad that you did manage to get a successful install.

Cheers!
