### ISSUE TITLE
Error at SSH during install

### ISSUE THREAD

**Issue by Huusky** [REMnux/remnux-cli#13]
Getting this error

```
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

```user@remnux:~$ cat /var/cache/remnux/cli/v2020.41.2/saltstack.log | grep -a -C 5 "result: false"
    __run_num__: 632
    __sls__: remnux.tools.ssview
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ssview.remnux-tools-ssview-source'
    duration: 0.006
    result: false
    start_time: '00:51:15.319381'
  archive_|-remnux-tools-trid-archive_|-/usr/local/trid_linux_64_|-extracted:
    __id__: remnux-tools-trid-archive
    __run_num__: 609
    __sls__: remnux.tools.trid
--
    __run_num__: 644
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.remnux-tools'
    duration: 0.011
    result: false
    start_time: '00:51:20.170444'
  file_|-remnux-config-android-project-creator-permissions_|-/opt/AndroidProjectCreator/library_|-directory:
    __id__: remnux-config-android-project-creator-permissions
    __run_num__: 556
    __sls__: remnux.config.android-project-creator
--
    comment: Specified sha256 checksum for /usr/local/src/remnux/files/SSView.zip
      (8bafa359afa53984ed9809bbe2e848d6866a42edfc1b446c91841fd0b439e879) does not
      match actual checksum (4d2b244fff9524c26fa2d52cce763578a0a30e4ef7020435e744d3e5f4ddb44c)
    duration: 5435.966
    name: /usr/local/src/remnux/files/SSView.zip
    result: false
    start_time: '00:51:09.864119'
  file_|-remnux-tools-ssview-wrapper_|-/usr/local/bin/ssview_|-managed:
    __run_num__: 633
    __sls__: remnux.tools.ssview
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ssview.remnux-tools-ssview-archive'
    duration: 0.005
    result: false
    start_time: '00:51:15.337950'
  file_|-remnux-tools-swf-mastah-shebang_|-/usr/local/pdfxray_lite/swf_mastah.py_|-replace:
    __id__: remnux-tools-swf-mastah-shebang
    __run_num__: 595
    __sls__: remnux.tools.swf_mastah
--
    __run_num__: 698
    __sls__: remnux.dedicated
    changes: {}
    comment: 'One or more requisite failed: remnux.addon.remnux-addon-version-file'
    duration: 0.006
    result: false
    start_time: '00:51:23.271763'
  test_|-remnux-node-packages_|-remnux-node-packages_|-nop:
    __id__: remnux-node-packages
    __run_num__: 641
    __sls__: remnux.node-packages
--
    __sls__: remnux.tools
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ssview.remnux-tools-ssview-source,
      remnux.tools.ssview.remnux-tools-ssview-archive, remnux.tools.ssview.remnux-tools-ssview-wrapper'
    duration: 0.01
    result: false
    start_time: '00:51:17.315818'
  user_|-remnux-user-user_|-user_|-present:
    __id__: remnux-user-user
    __run_num__: 346
    __sls__: remnux.config.user
```

**Comment by lennyzeltser** [comment]
Looks like SSView file has changed on its author's website, and the hash REMnux was expecting no longer matched. I updated the hash to match the new file.

Please try the installation again. You can run `remnux upgrade` to complete the installation on the system where you encountered the error. 

I'd love to hear back from you to confirm that this worked.

**Comment by Huusky** [comment]
That fixed it, much appreciated.
