### ISSUE TITLE
errors upgrading to saltstack v2020.42.1

### ISSUE THREAD

**Issue by davidep** [REMnux/remnux-cli#14]
I'm getting error upgrading to the latest saltstack v2020.42.1

the errors triggers after: 
```
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

Buy by looking into it seem possibly related to this:
```
pip_|-r2pipe_|-r2pipe_|-installed:
    __id__: r2pipe
    __run_num__: 247
    __sls__: remnux.python-packages.r2pipe
    changes: {}
    comment: "Failed to install packages: r2pipe. Error: Collecting r2pipe\n  Downloading
      https://files.pythonhosted.org/packages/1d/08/c7f0a5e494ee2bf9c33bdd7e28f5a2a34ec0bd0466396fd2d27814517685/r2pipe-1.5.0.tar.gz\n
      \   Complete output from command python setup.py egg_info:\n    Traceback (most
      recent call last):\n      File \"<string>\", line 1, in <module>\n      File
      \"/tmp/pip-build-Sj126K/r2pipe/setup.py\", line 3, in <module>\n        import
      r2pipe\n      File \"r2pipe/__init__.py\", line 38, in <module>\n        from
      r2pipe.open_sync import open\n      File \"r2pipe/open_sync.py\", line 15, in
      <module>\n        from urllib.error import URLError\n    ImportError: No module
      named error\n    \n    ---------------------------------------- /usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12:
      CryptographyDeprecationWarning: Python 2 is no longer supported by the Python
      core team. Support for it is now deprecated in cryptography, and will be removed
      in a future release.\n  from cryptography import x509\nThe directory '/home/sansforensics/.cache/pip/http'
      or its parent directory is not owned by the current user and the cache has been
      disabled. Please check the permissions and owner of that directory. If executing
      pip with sudo, you may want sudo's -H flag.\nThe directory '/home/sansforensics/.cache/pip'
      or its parent directory is not owned by the current user and caching wheels
      has been disabled. check the permissions and owner of that directory. If executing
      pip with sudo, you may want sudo's -H flag.\nCommand \"python setup.py egg_info\"
      failed with error code 1 in /tmp/pip-build-Sj126K/r2pipe/"
    duration: 2892.305
    name: r2pipe
    result: false
    start_time: '08:38:56.344890

```

**Comment by digitalsleuth** [comment]
Hi @davidep , This is due to a recent update of r2pipe where they've removed all support for Python 2, and changed their build to support only Python 3.
I'm submitting the pull request to fix this now, but in the meantime, you can run the following to install:
`sudo python3 -m pip install r2pipe`

Cheers

**Comment by lennyzeltser** [comment]
Thanks for [fixing](https://github.com/REMnux/salt-states/pull/147) this, @digitalsleuth! I just signed and issue a new release to incorporate your change.

@davidep, you should be good to proceed now. You can run `remnux upgrade` to finish the installation.
