### ISSUE TITLE
Issue with Remnux Upgrade 

### ISSUE THREAD

**Issue by shyle6** [REMnux/remnux-cli#140]
I am having issue with Remnux upgrade. Below is the output of the upgrade commands. Before this I had ran the update command which was successful. This is a new VM created yesterday by importing the OVA file to VirtualBox.

> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: v2022.28.1

> downloading v2023.31.1
>> downloading remnux-salt-states-v2023.31.1.tar.gz.asc
>> downloading remnux-salt-states-v2023.31.1.tar.gz.sha256
>> downloading remnux-salt-states-v2023.31.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2023.31.1.tar.gz
> validating file remnux-salt-states-v2023.31.1.tar.gz
> validating signature for remnux-salt-states-v2023.31.1.tar.gz.sha256
> extracting update remnux-salt-states-v2023.31.1.tar.gz
> using previous mode: dedicated
> upgrading/updating to v2023.31.1
>> Log file: /var/cache/remnux/cli/v2023.31.1/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Attaching the saltstack.log file as well. Please review.
 
[saltstack.log](https://github.com/REMnux/remnux-cli/files/12320893/saltstack.log)

**Comment by shyle6** [comment]
Just read and ran the below command as suggested by BoBeR182 under issue 136 and...

sudo pip install 'importlib_metadata==4.13.0'

....fixed my above issue, and I am fully updated now.
