### ISSUE TITLE
Upgrade to v2023.45.1 not working

### ISSUE THREAD

**Issue by tuttimann** [REMnux/remnux-cli#158]
Hi, my remnux upgrade to v2023.45.1 always fails.

Here is my saltstack.log file:
[saltstack.log](https://github.com/REMnux/remnux-cli/files/13670418/saltstack.log)

**Comment by Pir00t** [comment]
I'm having the same issue. Had an older version that failed on numerous levels using 'remnux upgrade/update' so downloaded the latest OVA. 

Running 'remnux upgrade' on the fresh OVA still fails to update - is this too big a jump in version (v2022.28.1 to v2023.45.1)? I've added the failed snips from saltstack.log

```
remnux@remnux:~$ grep -a 'result: false' -B 7 /var/cache/remnux/cli/v2023.45.1/saltstack.log 
        -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\\\"2.206\\\"
        -DXS_VERSION=\\\"2.206\\\" -fPIC \"-I/usr/lib/x86_64-linux-gnu/perl/5.30/CORE\"
        \ -Wall -Wno-comment   Lzma.c\n  PMQS/Compress-Raw-Lzma-2.206.tar.gz\n  /usr/bin/make
        -- NOT OK"
    comment: Command "cpan install Image::ExifTool" run
    duration: 204981.677
    name: cpan install Image::ExifTool
    result: false
--
    start_time: '08:42:38.402454'
  file_|-remnux-addon-version-file_|-/etc/remnux-version_|-managed:
    __run_num__: 805
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.perl-packages.remnux-perl-packages'
    duration: 0.005
    result: false
--
    start_time: '08:57:20.572748'
  test_|-remnux-dedicated_|-remnux-dedicated_|-nop:
    __run_num__: 862
    __sls__: remnux.dedicated
    changes: {}
    comment: 'One or more requisite failed: remnux.addon.remnux-addon-version-file'
    duration: 0.004
    result: false
--
    start_time: '08:46:15.061264'
  test_|-remnux-perl-packages_|-remnux-perl-packages_|-nop:
    __run_num__: 804
    __sls__: remnux.perl-packages
    changes: {}
    comment: 'One or more requisite failed: remnux.perl-packages.exiftool.remnux-perl-packages-exiftool'
    duration: 0.006
    result: false
```

**Comment by digitalsleuth** [comment]
Hi @tuttimann , it looks like you're having an issue with pip that's been making its rounds. Try running the following:
```bash
sudo python3 -m pip install --break-system-packages --force-reinstall protobuf==3.20.3
sudo python3 -m pip install --break-system-packages --force-reinstall setuptools==67.7.2
sudo python3 -m pip install --break-system-packages --force-reinstall typing_extensions>=4.5.0
```

This should fix your issue!

**Comment by digitalsleuth** [comment]
@Pir00t , can you attach your saltstack.log file? It looks like there might be an issue with exiftool being installed, so we'll have to look to see what's happening during that part of the installation.

**Comment by Pir00t** [comment]
Sure, I'll upload in a minute!

**Comment by Pir00t** [comment]
@digitalsleuth here you go [saltstack.log](https://github.com/REMnux/remnux-cli/files/13674426/saltstack.log)

**Comment by digitalsleuth** [comment]
@Pir00t It looks like your issue was caused by a missing requirement:
```bash
Lzma.xs:18:10: fatal error: lzma.h: No such file or directory
   18 | #include "lzma.h"
      |          ^~~~~~~~
compilation terminated.
```
Given that the issue here is different than yours, I'm going to open up a new Issue for this.

**Comment by tuttimann** [comment]
@digitalsleuth I tried with those 3 commands, but I am getting error messages for all of them:

```
Collecting protobuf==3.20.3
  Using cached protobuf-3.20.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
WARNING: Error parsing requirements for protobuf: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/protobuf-3.20.3.dist-info/METADATA'
WARNING: Error parsing requirements for pyelftools: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/METADATA'
WARNING: Error parsing requirements for setuptools: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/setuptools-67.8.0.dist-info/METADATA'
WARNING: Error parsing requirements for typing-extensions: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/typing_extensions-4.7.1.dist-info/METADATA'
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages
    Found existing installation: protobuf 3.20.3
ERROR: Cannot uninstall protobuf 3.20.3, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps protobuf==3.20.3'.

Collecting setuptools==67.7.2
  Using cached setuptools-67.7.2-py3-none-any.whl (1.1 MB)
WARNING: Error parsing requirements for protobuf: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/protobuf-3.20.3.dist-info/METADATA'
WARNING: Error parsing requirements for pyelftools: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/METADATA'
WARNING: Error parsing requirements for setuptools: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/setuptools-67.8.0.dist-info/METADATA'
WARNING: Error parsing requirements for typing-extensions: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/typing_extensions-4.7.1.dist-info/METADATA'
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages
    Found existing installation: setuptools 67.8.0
ERROR: Cannot uninstall setuptools 67.8.0, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps setuptools==67.8.0'.

WARNING: Error parsing requirements for protobuf: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/protobuf-3.20.3.dist-info/METADATA'
WARNING: Error parsing requirements for pyelftools: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/METADATA'
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chepy 5.1.0 requires pyOpenSSL, which is not installed.
mwcp 3.13.0 requires pyelftools, which is not installed.
chepy 5.1.0 requires pyjwt==1.7.1, but you have pyjwt 2.0.1 which is incompatible.
droidlysis 3.4.5 requires python-magic==0.4.12, but you have python-magic 0.4.27 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Comment by digitalsleuth** [comment]
Can you show me the actual command you typed? If you used the --break-system-packages then you shouldn't be getting that error.

**Comment by tuttimann** [comment]
Sure, this is i.e. the command and output for the first command:

```
sudo python3 -m pip install --break-system-packages --force-reinstall protobuf==3.20.3
[sudo] password for:
Collecting protobuf==3.20.3
  Using cached protobuf-3.20.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
WARNING: Error parsing requirements for protobuf: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/protobuf-3.20.3.dist-info/METADATA'
WARNING: Error parsing requirements for pyelftools: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/METADATA'
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages
    Found existing installation: protobuf 3.20.3
ERROR: Cannot uninstall protobuf 3.20.3, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps protobuf==3.20.3'.

```
Please tell me if you also need the other 2

**Comment by digitalsleuth** [comment]
Well, given the options available at the moment, I would either suggest uninstalling then re-installing, other using the "--no-deps" option they recommend simply to get it installed, then re-run the "--force-reinstall" without the "--no-deps". That should put you back to a normal state.

**Comment by gusgravious** [comment]
Was going to submit an issue though I suspect I have the same issue.

I tried this in VMWare Workstation, VirtualBox and downloaded a clean OVA file running the `remnux upgrade` command and getting the exact same result on two different systems.

```bash
remnux@remnux:~$ remnux upgrade
> remnux-cli@1.3.9.1.g849ae31
> remnux-version: v2023.40.2

> downloading v2023.45.1
>> downloading remnux-salt-states-v2023.45.1.tar.gz.asc
>> downloading remnux-salt-states-v2023.45.1.tar.gz.sha256
>> downloading remnux-salt-states-v2023.45.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2023.45.1.tar.gz
> validating file remnux-salt-states-v2023.45.1.tar.gz
> validating signature for remnux-salt-states-v2023.45.1.tar.gz.sha256
> extracting update remnux-salt-states-v2023.45.1.tar.gz
> using previous mode: dedicated
> upgrading/updating to v2023.45.1
>> Log file: /var/cache/remnux/cli/v2023.45.1/saltstack.log
...
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```

I checked the saltstack.log file and while I have little to no idea how it works its fairly obvious that the issue is with pip/python.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/13689912/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @gusgravious , yes yours is related to the pip issue. Can you try the commands listed [here](https://github.com/REMnux/remnux-cli/issues/158#issuecomment-1855935468) and, if necessary complete the uninstall and reinstall to get them to work, then try your install again.

Cheers!

**Comment by gusgravious** [comment]
First thing tomorrow, in no shape for error searching right now ;) I'll get back to you

**Comment by gusgravious** [comment]
Well, there were a few different warnings and error messages between different versions of remnux and VMWare Virtualbox installs, though after following along with "pip" suggestions and whatnot it sees that both upgrade and update works. At least in a clean install from available OVA.

I had more details and examples of outputs, though I managed to close the browser before posting. So, the suggested workaround (with some additional suggested pip commands) I can now upgrade and update.

**Comment by gusgravious** [comment]
Turns out I spoke to soon. This only solves the issue in a fresh install from OVA file in VMWare.

Trying to use the same approach in VMWare or VirtualBox with previous installs of Remnux does not work. It breaks at the exact same point. I'll try to uninstall and reinstall tomorrow, meanwhile a "dist-upgrade" was suggested to me in another channel. Just FYI

**Comment by gusgravious** [comment]
So the next step was to try to uninstall then reinstall, this does not go very smoothly:
`ERROR: Cannot uninstall protobuf 4.24.4, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps protobuf==4.24.4'.`

The "force-reinstall" errors out with the same message. So it feels like there will be a bit of "manual labor" in order to resolve this.

**Comment by digitalsleuth** [comment]
Sorry for the delay in getting back to you, been a busy week. You can try running:
```bash
sudo python3 -m pip install --break-system-packages --force-reinstall --no-deps typing_packages
sudo python3 -m pip install --break-system-packages --force-reinstall --no-deps protobuf
sudo python3 -m pip uninstall typing_packages
sudo python3 -m pip uninstall protobuf
```

Then you should be able to run the install again. These commands will force the package to install properly, possibly with limitations, but just enough to allow you to then properly uninstall the package without errors. Then the installer will fully install the necessary packages.

**Comment by gusgravious** [comment]
No worries, same problem here :)

```bash
remnux@remnux:~$ sudo python3 -m pip install --break-system-packages --force-reinstall --no-deps typing_packages
ERROR: Could not find a version that satisfies the requirement typing_packages (from versions: none)
ERROR: No matching distribution found for typing_packages
remnux@remnux:~$ sudo python3 -m pip install --break-system-packages --force-reinstall --no-deps protobuf
Collecting protobuf
  Using cached protobuf-4.25.1-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Using cached protobuf-4.25.1-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages
    Found existing installation: protobuf 4.24.4
ERROR: Cannot uninstall protobuf 4.24.4, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps protobuf==4.24.4'.
remnux@remnux:~$ sudo python3 -m pip uninstall protobuf
WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages
Found existing installation: protobuf 4.24.4
ERROR: Cannot uninstall protobuf 4.24.4, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps protobuf==4.24.4'.
```
The obvious problem I see is the problem with uninstalling protobuf which seems to fail? Also I'm going to take a wild guess and say that typing_packages should be typing_extensions, so:

```bash
remnux@remnux:~$ sudo python3 -m pip install --break-system-packages --force-reinstall --no-deps typing_extensions
Collecting typing_extensions
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Installing collected packages: typing_extensions
  Attempting uninstall: typing_extensions
    WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages
    Found existing installation: typing-extensions 4.8.0
ERROR: Cannot uninstall typing-extensions 4.8.0, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps typing-extensions==4.8.0'.
```
It seems that if the solution is to uninstall then reinstall, I'm caught in a bit of a jam here where I cannot install until I've uninstalled and I cant uninstall because something broke.

I can just flush the VMs and start from a new machine though it would be nice to see why this does not work in my older VMs

**Comment by digitalsleuth** [comment]
Sorry, the typo in the typing_extensions was my fault, too many thoughts running in my head at the same time :)
There's another way to fix this, we'll just have to trick pip into thinking it has what it needs:
```bash
sudo touch /usr/local/lib/python3.8/dist-packages/protobuf-4.24.4.dist-info/METADATA
sudo touch /usr/local/lib/python3.8/dist-packages/protobuf-4.24.4.dist-info/RECORD
sudo touch /usr/local/lib/python3.8/dist-packages/typing_extensions-4.8.0.dist-info/METADATA
sudo touch /usr/local/lib/python3.8/dist-packages/typing_extensions-4.8.0.dist-info/RECORD
```
Try giving that a shot before you start from scratch, then re-run the pip commands to install as previous.

**Comment by gusgravious** [comment]
Who in their right mind would complain over free tech-support? 

Yeah, did not consider all it needed were empty files 😄 The file creation seems to solve `pip`s initial complaints

```bash
remnux@remnux:~$ sudo touch /usr/local/lib/python3.8/dist-packages/protobuf-4.24.4.dist-info/METADATA
remnux@remnux:~$ sudo touch /usr/local/lib/python3.8/dist-packages/protobuf-4.24.4.dist-info/RECORD
remnux@remnux:~$ sudo touch /usr/local/lib/python3.8/dist-packages/typing_extensions-4.8.0.dist-info/METADATA
remnux@remnux:~$ sudo touch /usr/local/lib/python3.8/dist-packages/typing_extensions-4.8.0.dist-info/RECORD

remnux@remnux:~$ sudo python3 -m pip install --break-system-packages --force-reinstall protobuf==3.20.3
Collecting protobuf==3.20.3
  Using cached protobuf-3.20.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
DEPRECATION: distro-info 0.23ubuntu1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.24.4
    Can''t uninstall 'protobuf'. No files were found to uninstall.
Successfully installed protobuf-3.20.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

remnux@remnux:~$ sudo python3 -m pip install --break-system-packages --force-reinstall setuptools==67.7.2
Collecting setuptools==67.7.2
  Using cached setuptools-67.7.2-py3-none-any.whl (1.1 MB)
DEPRECATION: distro-info 0.23ubuntu1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 67.7.2
    Uninstalling setuptools-67.7.2:
      Successfully uninstalled setuptools-67.7.2
ERROR: pip''s dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
qiling 1.4.6 requires unicorn>=2.0.1, but you have unicorn 1.0.2 which is incompatible.
thug 5.7 requires charset-normalizer==3.2.0, but you have charset-normalizer 2.1.1 which is incompatible.
thug 5.7 requires importlib-resources==6.0.1; python_version < "3.9", but you have importlib-resources 5.13.0 which is incompatible.
thug 5.7 requires python-magic==0.4.27, but you have python-magic 0.4.12 which is incompatible.
Successfully installed setuptools-67.7.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

remnux@remnux:~$ sudo python3 -m pip install --break-system-packages --force-reinstall typing_extensions>=4.5.0
DEPRECATION: distro-info 0.23ubuntu1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
ERROR: pip''s dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rich 9.13.0 requires typing-extensions<4.0.0,>=3.7.4, but you have typing-extensions 4.9.0 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```
I find it quite confusing how you can fail to uninstall since you don't find any files yet manage to successfully uninstall. Anyway, I have to round this up pretty early tonight so regardless of any complaints above i tossed in the "remnux upgrade" command and well see how that plays out.
Big thanks four your help, much appreciated!

**Comment by gusgravious** [comment]
```bash
>> COMPLETED SUCCESSFULLY! Success: 861, Failure: 0
>> Please reboot to make sure all settings go into effect.
```
So I may have broke something else though it seems to have worked. In other words, case closed?

**Comment by digitalsleuth** [comment]
With what you posted above, you didn't actually break anything, pip just complains a lot. If the install completed successfully, it means that everything should now be in the proper state. 

Cheers!

**Comment by gusgravious** [comment]
I tried to "copy-paste" fix my VMWare Workstation install and it of course will not finish the upgrade. I'll have a look at the saltstack.log and get back to you. But the VirtualBox install finished both upgrade and update without errors.

**Comment by gusgravious** [comment]
After applying the same logic to the VMware machine, force reinstalling typing_extensions everything worked out. Thanks for the help and patience!

**Comment by digitalsleuth** [comment]
I believe we should be able to close this issue now, unless you're still having this issue, @tuttimann ?

**Comment by tuttimann** [comment]
Yes, it can be closed. Thanks for your support.
