### ISSUE TITLE
Installation of Remnux on Ubuntu 20.04 - Update returned exit code not zero

### ISSUE THREAD

**Issue by samalder09** [REMnux/remnux-cli#175]
When attempting to run an install of Remnux on Ubuntu 20.04 using 'sudo remnux install --mode=addon, I am receiving failures at the same point of installation. The output that is presented at the error is:

">> Running: remnux-node-packages
>> Running: cpan install Net::SSLeay
>> Running: cpan install Image::ExifTool
>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.
To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.
For assistance go to https://github.com/REMnux/remnux-cli/issues"

The error message appears at ">> Running: remnux-perl-packages" every time an install is attempted. I have attempted new hosts, updating/upgrading OS tools, but no luck. I have zipped and attached the saltstack.log file. Would it be possible to look into the reason for this please? I've never encountered an issue running the installer using this method previously.

Thank you in advance!

[saltstack.zip](https://github.com/REMnux/remnux-cli/files/15109533/saltstack.zip)

**Comment by digitalsleuth** [comment]
Hi @samalder09, it looks like your error was caused by an `SSL: CERTIFICATE_VERIFY_FAILED` error when attempting to download two packages:
```bash
# [ERROR   ] Failed to cache https://download.docker.com/linux/ubuntu/gpg: Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007) reading /linux/ubuntu/gpg
# [ERROR   ] Failed to cache https://www.mitec.cz/Downloads/SSView.zip: Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007) reading /Downloads/SSView.zip
```

Can you confirm that the date/time inside the instance is set correctly? Sometimes, if the date of the request is much earlier or much later than the date/time on the server, the certificate validation may not succeed. Additionally, given that you're setting this up in an EC2 instance, it is possible that you've fallen victim to another issue identified on the [AWS GitHub page](https://github.com/aws/aws-cli/issues/2690#issuecomment-497856869). 

You can try confirming the date/time and reviewing the comment thread linked above to see if that resolves your issue. Please let us know how it goes!
