### ISSUE TITLE
Trouble Installing as Addon with Zscaler

### ISSUE THREAD

**Issue by scottlussier** [REMnux/remnux-cli#181]
I am trying to use "sudo remnux install --mode=addon" from an Ubuntu 20.04 VM on my Windows system that has a Zscaler client on it.  I installed the Zscaler root CA (I think).  The error is:

```
request to https://api.github.com/repos/REMnux/salt-states/releases failed, reason: unable to get local issuer certificate
HttpError: request to https://api.github.com/repos/REMnux/salt-states/releases failed, reason: unable to get local issuer certificate
    at /snapshot/remnux-cli/node_modules/@octokit/request/dist-node/index.js:107:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getValidReleases (/snapshot/remnux-cli/remnux-cli.js:295:18)
    at async run (/snapshot/remnux-cli/remnux-cli.js:740:26)
    at async main (/snapshot/remnux-cli/remnux-cli.js:780:5)
```

There is no saltstack.log file in /var/cache/remnux/cli.

**Comment by digitalsleuth** [comment]
Hi @scottlussier , are you able to browse or reach any other https sites from that Ubuntu 20.04 VM? And is there any chance you require access to pass through a proxy to do this?

**Comment by scottlussier** [comment]
> Hi @scottlussier , are you able to browse or reach any other https sites from that Ubuntu 20.04 VM? And is there any chance you require access to pass through a proxy to do this?

Hi!  Yes on the first question (for instance I am able to do "wget https://REMnux.org/remnux-cli") and not that I know of on the second question.

**Comment by digitalsleuth** [comment]
@scottlussier Can you try the install process again, just to see that it was not a temporary connectivity issue?

**Comment by scottlussier** [comment]
> @scottlussier Can you try the install process again, just to see that it was not a temporary connectivity issue?

Hi, no luck!

```
user@ubuntu:~$ sudo remnux install --mode=addon
> remnux-cli@1.3.9.1.g849ae31
> remnux-version: notinstalled

> mode: addon
Installing and configuring SaltStack properly ...

request to https://api.github.com/repos/REMnux/salt-states/releases failed, reason: unable to get local issuer certificate
HttpError: request to https://api.github.com/repos/REMnux/salt-states/releases failed, reason: unable to get local issuer certificate
    at /snapshot/remnux-cli/node_modules/@octokit/request/dist-node/index.js:107:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getValidReleases (/snapshot/remnux-cli/remnux-cli.js:295:18)
    at async run (/snapshot/remnux-cli/remnux-cli.js:740:26)
    at async main (/snapshot/remnux-cli/remnux-cli.js:780:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

user@ubuntu:~$
```

**Comment by digitalsleuth** [comment]
Well it looks like there might be some potential fixes for this issue. Given that this error originates with the Octokit node module, it's possible that the issue could be with Octokit. To see if that's part of the issue, you could try using [cast](https://github.com/ekristen/cast) to install REMnux and see if you have the same issue.

Otherwise, I would recommend you attempt to install both the intermediate and root certificates in your Ubuntu VM (if you have both). This _should_ also fix this issue, then you can try the install again with the remnux cli or with cast.

**Comment by lennyzeltser** [comment]
@scottlussier, to expand on what @digitalsleuth wrote earlier: The standard REMnux installer has a hard time with non-transparent proxies, and it's likely that your Zscaler configuration is triggering that issue. A few ideas to try are outlined [here](https://docs.remnux.org/tips/remnux-config-tips#behind-proxy).
