### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by futex** [REMnux/remnux-cli#183]
Hell, i wanted to upgrade my Remnux VM (Ubuntu 20.04) and got these errors:

`>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: away-from-the-dog
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
`

I can´t find the glue. 
Other questions, is it possible to blacklist a package? And, is Ubuntu 22.04 or 24.04 is supported?

Thanks you!

[saltstack.zip](https://github.com/user-attachments/files/16132449/saltstack.zip)

**Comment by digitalsleuth** [comment]
Hi @futex It looks like most of the issues are caused by some Python 3 errors with pip. To resolve these errors, you can run the following commands:
```bash
sudo touch /usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/METADATA
sudo touch /usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/RECORD
sudo touch /usr/local/lib/python3.8/dist-packages/yara_python-4.3.1.dist-info/METADATA
sudo touch /usr/local/lib/python3.8/dist-packages/yara_python-4.3.1.dist-info/RECORD
```

There was however another error which occurred during the cloning of the Python 2 version of Volatility, it looks as if there was a connectivity issue. This may have been a temporary / momentary issue, and should be resolved if the above issues are fixed and the install is run again.
```bash
  Running command git clone -q https://github.com/volatilityfoundation/volatility.git /tmp/pip-req-build-tlvTHz
  fatal: the remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
```

As for Ubuntu support, unfortunately Ubuntu 22 and 24 are not yet supported, but should be in the future.

**Comment by futex** [comment]
Thanks you, i have try your commands but i still having a crash just after the running of ssh like previously.

[saltstack.zip](https://github.com/user-attachments/files/16139210/saltstack.zip)

**Comment by digitalsleuth** [comment]
Hi @futex , it looks like the remaining issues focus around two areas:
- The setup.cfg files for each of the packages is not up to the PEP8 standard for the naming convention of sections
- Pylibemu is failing due to an incompatibility with the setuptools version.

Can you provide the output of the following command:
```bash
sudo python3 -m pip list
```

Feel free to redact anything you don't want shared, but I'm primarily looking for the versions of `wheel`, `setuptools`, and `pip`.

I will look into a solution for these, but it looks like for now, the quickest way may be to change your current version of setuptools. I won't know yet which version will work to support the installation, but I'm looking into it.

**Comment by futex** [comment]
Sure, here is the output of the command. How do you guess that? I read the saltstack log and i just see some remnux packages failed but i don´t find the reason. Is it possible also to "blacklist" a package, or to install only one?
[pip.txt](https://github.com/user-attachments/files/16156260/pip.txt)

**Comment by olokos** [comment]
![image](https://github.com/user-attachments/assets/88d37665-a24a-4556-bb36-0f313ba24e1c)
![image](https://github.com/user-attachments/assets/392afaa8-95a8-4508-91e8-03b559eb16b5)

`remnux-v7.ova`, after performing `apt update` and `apt upgrade`, also fails with `remnux update at the end, despite in general seems like it did update nearly all of the previous things.

**Comment by olokos** [comment]
https://forum.level1techs.com/t/installing-remnux-as-a-proxmox-vm-build-from-scratch/215903/1

Downgrading setuptools and breaking the env for a moment, does allow to successfully work around this bug though, as discovered here:
https://forum.level1techs.com/t/installing-remnux-as-a-proxmox-vm-build-from-scratch/215903/1

Apparently it was possible to work around it with `sudo python3 -m pip install setuptools==58.3.0`.
But as it is now, it seems that the issue remains similar, if not the same, even with this workaround.
![image](https://github.com/user-attachments/assets/9bb1ba6f-d26c-4334-8974-60c7299921bd)


I think it could be as `remnux update` itself, does update `systemtools` on its own during the process, so even if I manually downgraded to 58.3.0, `remnux update` will still update it to 60+, before ssh is installed, causing the issue again, despite the previous workaround.

I agree that the `saltstack.txt` is gigantic, I tried `| grep error` but the output was irrelevant to the actual errors we are interested in, as a result, I'm not sure how I could look for errors in `saltstack.txt` to provide more details than I have already.

On the other hand, when I installed the older setuptools in second terminal, after `remnux update` installed `setuptools==67.7.2`, but before it installed ssh, I'm still getting the same error

**Comment by SpotlightForBugs** [comment]
what is the current status?

**Comment by olokos** [comment]
last update to repository was 11 months ago, so perhaps this project is abandoned, as the issue remains unchanged.

**Comment by digitalsleuth** [comment]
Hi @olokos and @SpotlightForBugs, the repository content isn't updated as it only houses the source code for the CLI tool, which is currently functioning as expected. The Issues section of this repository is used for us to track issues which may have occurred as a result of the installation of packages using the CLI. When the CLI finishes installing everything, regardless of success or failures, it always shows the last package attempted. In this case, it happens to be `ssh`. If there is an error afterwards, the message simply indicates that there was an error during the installation process of at least one package, and provides you the location of the log file to review, or to provide to us for review.

In order for us to accurately resolve any issue you're currently experiencing, we would appreciate it if you could upload your saltstack.log file so we can review it for a resolution. 

Cheers!
