### ISSUE TITLE
sudo remnux install ended with error

### ISSUE THREAD

**Issue by MottiKumar** [REMnux/remnux-cli#185]
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

**Comment by MottiKumar** [comment]
remnux@remnux:~$ cat /var/cache/remnux/cli/v2024.28.1/saltstack.log | tail -60
        - pip==24.1.2
        - setuptools==67.7.2
        - PyYAML==6.0.1
        - six==1.16.0
        - pkg_resources==0.0.0
        old:
        - pkg-resources==0.0.0
        - setuptools==44.0.0
        - wheel==0.34.2
        - pip==20.0.2
    comment: Created new virtualenv
    duration: 4416.218
    name: /opt/qiling
    result: true
    start_time: '00:20:55.553905'
  virtualenv_|-remnux-python3-packages-speakeasy-virtualenv_|-/opt/speakeasy_|-managed:
    __id__: remnux-python3-packages-speakeasy-virtualenv
    __run_num__: 389
    __sls__: remnux.python3-packages.speakeasy
    changes:
      new: ''
      packages:
        new:
        - wheel==0.38.4
        - setuptools==67.7.2
        - pkg_resources==0.0.0
        - pip==24.1.2
        old:
        - pkg-resources==0.0.0
        - setuptools==44.0.0
        - wheel==0.34.2
        - pip==20.0.2
    comment: Created new virtualenv
    duration: 3341.944
    name: /opt/speakeasy
    result: true
    start_time: '00:20:40.327441'
  virtualenv_|-remnux-python3-packages-thug-virtualenv_|-/opt/thug_|-managed:
    __id__: remnux-python3-packages-thug-virtualenv
    __run_num__: 341
    __sls__: remnux.python3-packages.thug
    changes:
      new: ''
      packages:
        new:
        - wheel==0.38.4
        - yara-python==4.5.1
        - pip==24.1.2
        - setuptools==67.7.2
        - pkg_resources==0.0.0
        old:
        - pkg-resources==0.0.0
        - setuptools==44.0.0
        - wheel==0.34.2
        - pip==20.0.2
    comment: Created new virtualenv
    duration: 5899.257
    name: /opt/thug
    result: true
    start_time: '00:17:15.667672'

**Comment by MottiKumar** [comment]
Tried both Update and Upgrade too and also ended up with same error!

**Comment by MottiKumar** [comment]
[saltstack.log](https://github.com/user-attachments/files/16216636/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @MottiKumar , it looks like the issue you're having is due to a proxy communication error. You can try reviewing the [proxy configuration](https://docs.remnux.org/tips/remnux-config-tips#behind-proxy) section in the docs, and it may help resolve your issue.

Cheers!
