### ISSUE TITLE
install REMnux as addon with cast failed

### ISSUE THREAD

**Issue by knight-scott** [REMnux/remnux-cli#187]
`sudo cast install --mode=addon remnux/salt-states` resulted in error. 

```
WARN[0431] first failed state                            comment="One or more requisite failed: remnux.scripts.emldump.remnux-scripts-emldump-binary" component=installer run_num=484 sls=remnux.scripts.emldump
INFO[0431] statistics                                    component=installer failed=14 success=817 total=831
INFO[0431] salt-call completed but had failed states     component=installer
FATA[0431] salt-call completed but had failed states    
siftforensics@siftworkstation: ~
$ remnux version
> remnux-cli@1.3.9.1.g849ae31
> remnux-version: notinstalled

```
I tried using 
`sudo remnux install --mode=addon`
and received an error as well:
```

>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

```
[saltstack.log](https://github.com/user-attachments/files/16326340/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @knight-scott , it looks like the issue is due something caused by a previous pip version. You can run the following commands to fix the issue:
```bash
sudo touch /usr/local/lib/python3.8/dist-packages/yara_python-4.5.0.dist-info/METADATA
sudo touch /usr/local/lib/python3.8/dist-packages/yara_python-4.5.0.dist-info/RECORD
```
After that you can run the installer again and everything should work out fine.

Please let us know how it goes. Cheers!

**Comment by knight-scott** [comment]
Thank you, that worked.
