### ISSUE TITLE
WSL Ubuntu 20.04 addon ends with exit code not zero

### ISSUE THREAD

**Issue by scurvysourdebugger** [REMnux/remnux-cli#188]
The installer always seems to fail at this step:
Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
[saltstack.log](https://github.com/user-attachments/files/16922148/saltstack.log)

It's a newly installed and updated Ubuntu 20.04 running in WSL with windows 11
Any ideas?

**Comment by digitalsleuth** [comment]
@scurvysourdebugger Can you send us your saltstack.log file so we can review, and can you provide the command you used to initiate the installation?

Cheers!

**Comment by scurvysourdebugger** [comment]
I used `sudo remnux install --mode=addon` to run the installer.
I can see the link to the saltstack log got kinda hidden by the github link so here it is again: 
[saltstack.log](https://github.com/user-attachments/files/16929182/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @scurvysourdebugger, It looks like the biggest issue in your case is due to a recent drop of Python 2 support for pyftpdlib, which is a requirement for the current version of flare-fakenet-ng (which is not yet fully ported to Python 3).
The second issue, malchive, will be resolved by the recently submitted PR, as they've changed dependencies for Python 3 to 3.11, which is not "available" in Ubuntu Focal.

And the third error, a "venv" configuration error, is also going to be resolved by the recently submitted PR.

I will look at the fakenet issue, and submit a PR to temporarily remove it until the Python 3 compatible version is fully released.

**Comment by scurvysourdebugger** [comment]
Thanks a lot for looking into it. I tried again but it still fails at the same point. Is there anything I should change with regards to python, or try it from a completely fresh ubuntu install?
I'll add the new saltstack log here just in case: 
[saltstack.log](https://github.com/user-attachments/files/16981335/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @scurvysourdebugger , it looks like your install had two issues, one of which was just fixed with the removal of fakenet. The other is an issue during the installation of the `dissect` package, which I'm working on fixing now. I'll let you know once the PR is finished and merged. Cheers!
