### ISSUE TITLE
Upgrade from 2024.28.1 - 2024.41.4 Update returned exit code not zero

### ISSUE THREAD

**Issue by getrdun1010** [REMnux/remnux-cli#190]
Hello,

When upgrading I get ,

pdate returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

I have run the following to try to fix but no go.
sudo apt update
sudo apt autoremove
sudo apt --fix-broken install

Please help.  Attached is the salt log.

Thanks a bunch!
[saltstack.log](https://github.com/user-attachments/files/17343503/saltstack.log)

**Comment by lennyzeltser** [comment]
@getrdun1010, please try the following workaround:

```
sudo touch /usr/local/lib/python3.8/dist-packages/pefile-2023.2.7.dist-info/METADATA
```

Then run `remnux upgrade` again.
