### ISSUE TITLE
remnux install --mode=addon, Error: Update returned exit code not zero 

### ISSUE THREAD

**Issue by smartzh** [REMnux/remnux-cli#191]
[saltstack.log](https://github.com/user-attachments/files/17466720/saltstack.log)

version v2024.41.42.1

>> Running: make install
>> Running: /usr/local/src/remnux/exiftool
>> Running: /usr/local/src/remnux/files/Image-ExifTool-12.98.tar.gz
>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

**Comment by digitalsleuth** [comment]
Hi @smartzh It appears that the issue you're experiencing centers around a python package with the version '0.23ubuntu1', which is no longer a "valid" version in the pypi/pip world.
To resolve this, you can run the following:

`sudo python3 -m pip install --upgrade setuptools wheel pip`

After that you can try your install process again and it should work.

**Comment by smartzh** [comment]
[saltstack.log](https://github.com/user-attachments/files/17473020/saltstack.log)

@digitalsleuth same error as follow:

 sudo python3 -m pip install --upgrade setuptools wheel pip
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (75.2.0)
Requirement already satisfied: wheel in /usr/local/lib/python3.8/dist-packages (0.44.0)
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (24.2)
WARNING: Error parsing dependencies of distro-info: Invalid version: '0.23ubuntu1'
WARNING: Error parsing dependencies of python-debian: Invalid version: '0.1.36ubuntu1'
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

sudo remnux install --mode=addon

>> Running: /usr/local/src/remnux/exiftool
>> Running: /usr/local/src/remnux/files/Image-ExifTool-12.98.tar.gz
>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
