### ISSUE TITLE
[11/12/2024] REMnux failed to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by KlimHazzard** [REMnux/remnux-cli#196]
Trying to download REMnux on Ubuntu using the following command `sudo remnux install --mode=addon` and I get the following error

```
> remnux-cli@1.4.3.1.g2137384
> remnux-version: notinstalled

> mode: addon
> downloading v2024.44.3
>> downloading remnux-salt-states-v2024.44.3.tar.gz.asc
>> downloading remnux-salt-states-v2024.44.3.tar.gz.sha256
>> downloading remnux-salt-states-v2024.44.3.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2024.44.3.tar.gz
> validating file remnux-salt-states-v2024.44.3.tar.gz

Hashes for remnux-salt-states-v2024.44.3.tar.gz do not match. Expected: . Actual: eaa5a44346030b7a96f8a4531cc21976527fd88483c5a3e11f0670cc87f2db69  /tmp/remnux-salt-states-v2024.44.3.tar.gz
.
Error: Hashes for remnux-salt-states-v2024.44.3.tar.gz do not match. Expected: . Actual: eaa5a44346030b7a96f8a4531cc21976527fd88483c5a3e11f0670cc87f2db69  /tmp/remnux-salt-states-v2024.44.3.tar.gz
.
    at validateFile (/snapshot/remnux-cli/remnux-cli.js:407:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async downloadUpdate (/snapshot/remnux-cli/remnux-cli.js:474:3)
    at async run (/snapshot/remnux-cli/remnux-cli.js:748:5)
    at async main (/snapshot/remnux-cli/remnux-cli.js:771:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

```

**Comment by lennyzeltser** [comment]
@KlimHazzard, I'm wondering whether something upstream from your network connection is interfering with the download. Are you behind a web proxy, by any chance? The REMnux installer [doesn't presently work with proxies](https://docs.remnux.org/tips/remnux-config-tips#behind-proxy).

**Comment by KlimHazzard** [comment]
Not behind a web proxy. I have a VPN that I use but in these scenarios when debugging issues I'll switch it off to see if it fixes anything and it doesn't fix it :(. Would having the VPN on during the installation process (when I run the command `sudo remnux install --mode=addon`) permanently effect the installation process to where it wouldn't work afterwards?

**Comment by lennyzeltser** [comment]
Great, please give it a try. It's fine to run the REMnux installer command multiple times.

**Comment by KlimHazzard** [comment]
Currently whipped up a fresh Ubuntu install and tried this time without a VPN on the entire time during the Ubuntu installation process AND the following REMnux installation process. It seems to be running fine so far! (I also ran `sudo remnux install` instead)

As for the previous Ubuntu install, I can't seem to run `sudo remnux install --mode=addon` without having the same error pop up.

I'll update if it ~completes fully~ it didn't complete fully, it got up to the following

```
>> Running: /etc/ssh/sshd_config
>> Running: away-from-the-dog
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```

**Comment by KlimHazzard** [comment]
Well I was prompted to update my new version of Ubuntu (the ISO used is 20.04.6) using the package manager and restarted the VM. It seems like it might have half installed REMnux (?). It changed the background in Ubuntu to the REMnux background and some of the packages are there. But when I run `sudo remnux install` again I get the same kind of error

```
.
.
.
>> Running: away-from-the-dog
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```

Which seems like SSH is the problem?

**Comment by KlimHazzard** [comment]
ALSO the other Ubuntu VM still has the original same salt-states error stated as before when running either commands, even if a VPN isn't running
`sudo remnux install`
`sudo remnux install --mode=addon`

**Comment by digitalsleuth** [comment]
Hi @KlimHazzard , the `ssh` state is just the last state to run in the list of installations, not necessarily the one with the issue itself. The "Error" doesn't present until after all states have been run. Would you be able to provide the saltstack.log file so we can do some troubleshooting?

**Comment by KlimHazzard** [comment]
Sure, according to the information in the error log it says "please review the saltstack.log file under /var/cache/remnux/cli", but I can't seem to find this log file in the directory

```
remnux@ubuntu:/var/cache/remnux/cli/v2024.44.3$ ls
remnux-salt-states-v2024.44.3.tar.gz
remnux-salt-states-v2024.44.3.tar.gz.asc
remnux-salt-states-v2024.44.3.tar.gz.sha256
remnux-salt-states-v2024.44.3.tar.gz.sha256.asc
```

~How can I retrieve the saltstack.log (mind you this is just a fresh install of Ubuntu)?~

UPDATE: Found the saltstack.log, since I'm referring to two VMs where I'm instally REMnux here, it was in the second VM

**Comment by KlimHazzard** [comment]
Found the saltstack.log @digitalsleuth 
[saltstack.log](https://github.com/user-attachments/files/17744146/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @KlimHazzard , my apologies for not getting back to you sooner. It looks like the error you're having is related to an install issue with pycryptodome. Can you try running the following:
```bash
sudo touch /usr/local/lib/python3.8/dist-packages/pycryptodome-3.21.0.dist-info/METADATA
sudo touch /usr/local/lib/python3.8/dist-packages/pycryptodome-3.21.0.dist-info/RECORD
```
Once that's done, you should be able to retry your installation.

**Comment by KlimHazzard** [comment]
Thanks for the response @digitalsleuth I unfortunately still get the same problem. I tried it several times reverting to the previous snapshot before remnux installing and then trying a variation of actions like updating Ubuntu 20.04 software packages. Here's the excerpt of my console where it stops.

```
.
.
.
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.
.
.
.
```
Here is the latest saltstack log file
[saltstack.log](https://github.com/user-attachments/files/17806983/saltstack.log). Thanks for looking into this, please advise anything you notice between this saltstack.log and the previous one I submitted above

**Comment by digitalsleuth** [comment]
Hi again @KlimHazzard , the error in this saltstack.log file is the same as the previous, so it's possible that you've made the change, got a different error, reverted to a snapshot but didn't apply the fix to that, and then got the previous error.

In your current snapshot / state, can you please run the commands from [my previous comment](https://github.com/REMnux/remnux-cli/issues/196#issuecomment-2484146161) and if you end up with an error, please attach that log file?

Cheers!

**Comment by KlimHazzard** [comment]
I'm pretty sure I used those commands before I ran `sudo remnux install` and sent you the log. Here's a screenshot of me doing it again

Before
![Screenshot 2024-11-18 201104](https://github.com/user-attachments/assets/6f08c911-7112-4bce-b088-e68a75a51019)

After. Are the files created from the `touch` command supposed to be gone after I run `sudo remnux install`?
![Screenshot 2024-11-18 202700](https://github.com/user-attachments/assets/73801f92-4aa1-4250-86dd-796908e8c0a1)

Attached is the saltstack log after this failure.
[saltstack.log](https://github.com/user-attachments/files/17809540/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @KlimHazzard , it looks like the errors from this log are two-fold:
- the first error is in regards to a temporary connectivity issue when attempting to install ViperMonkey, where the following occurs
```bash
# [ERROR   ] Failed to install packages: git+https://github.com/decalage2/ViperMonkey.git. Error: Collecting git+https://github.com/decalage2/ViperMonkey.git
  Cloning https://github.com/decalage2/ViperMonkey.git to /tmp/pip-req-build-uswtbV DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
  Running command git clone -q https://github.com/decalage2/ViperMonkey.git /tmp/pip-req-build-uswtbV
  error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  fatal: the remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
```

- the second error was again the pycryptodome error from before. You can try to do the following to remedy it this time around
```bash
sudo python3 -m pip install --force-reinstall --break-system-packages pycryptodome
```

This should remedy the pycryptodome by forcibly removing and re-installing properly so it can then be managed by other packages which need to.

**Comment by KlimHazzard** [comment]
Thanks for sticking with me on this @digitalsleuth. So I've installed 
`sudo python3 -m pip install --force-reinstall --break-system-packages pycryptodome`
![Screenshot 2024-11-20 152105](https://github.com/user-attachments/assets/5344fafc-81ae-4fe3-9214-e91122e38e17)

Is there something I should do to install ViperMonkey? I'm still getting the same error when I attempt to install remnux.

**Comment by digitalsleuth** [comment]
Glad to help! As for ViperMonkey, that's a different issue that we're currently dealing with right now. If you're only getting ViperMonkey as an error, you shouldn't need to worry about that, you'll be able to still use everything else. Once we address the issue, you will be able to upgrade to the next release without a problem.

**Comment by Identity9165** [comment]
for those getting same error, it was NextDNS for me because it blocks bbuseruploads.s3.amazonaws.com by threat intelligence feeds 💀 which blocks [apktools](https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.11.1.jar) download.

![Image](https://github.com/user-attachments/assets/22c65653-764a-4e9b-8497-0efc58b8ab3a)
