### ISSUE TITLE
Error in Upgrading the distro.

### ISSUE THREAD

**Issue by Promisecharles** [REMnux/remnux-cli#198]
I have tried everything possible to upgrade, even from the v2024.48.6 to now the v2024.48.7 was rolled out yet its not working. Here is the error i'm getting now.

remnux@remnux:/var/cache/remnux/cli$ ls
v2024.41.3  v2024.48.6  v2024.48.7
remnux@remnux:/var/cache/remnux/cli$ remnux upgrade
> remnux-cli@1.4.3.1.g2137384
> remnux-version: v2024.41.3

> downloading v2024.48.7
>> downloading remnux-salt-states-v2024.48.7.tar.gz.asc
>> downloading remnux-salt-states-v2024.48.7.tar.gz.sha256
>> downloading remnux-salt-states-v2024.48.7.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2024.48.7.tar.gz
> validating file remnux-salt-states-v2024.48.7.tar.gz

Hashes for remnux-salt-states-v2024.48.7.tar.gz do not match. Expected: . Actual: 9ad58c5bf0e903ab4534eaa001e9292fffb0fc18383226d7a53805f0adc015d9  /tmp/remnux-salt-states-v2024.48.7.tar.gz
.
Error: Hashes for remnux-salt-states-v2024.48.7.tar.gz do not match. Expected: . Actual: 9ad58c5bf0e903ab4534eaa001e9292fffb0fc18383226d7a53805f0adc015d9  /tmp/remnux-salt-states-v2024.48.7.tar.gz
.
    at validateFile (/snapshot/remnux-cli/remnux-cli.js:407:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async downloadUpdate (/snapshot/remnux-cli/remnux-cli.js:474:3)
    at async run (/snapshot/remnux-cli/remnux-cli.js:763:5)
    at async main (/snapshot/remnux-cli/remnux-cli.js:771:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

**Comment by digitalsleuth** [comment]
Hi @Promisecharles , are you perhaps behind a proxy with this attempt? If not, can you also take a look in your `/tmp` directory and see if that file still currently exists there? You may also need to run the `remnux upgrade` command using `sudo`.

Please let us know how this goes so we can make sure you're able to upgrade.

Cheers!

**Comment by Promisecharles** [comment]
![29 11 2024_12 09 31_REC](https://github.com/user-attachments/assets/1a83f866-2f09-47a3-a5ae-1189f8f64501)


This are the files in the /tmp directory.
