### ISSUE TITLE
New Install fails

### ISSUE THREAD

**Issue by calistouk** [REMnux/remnux-cli#199]
I get the following when trying to install as of today 13th Dec On ubuntu 20.04.6

>> Running: away-from-the-dog
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

Attached saltstack.log if this helps

[saltstack.zip](https://github.com/user-attachments/files/18131711/saltstack.zip)

**Comment by digitalsleuth** [comment]
Hi @calistouk , it looks like the root outlier possibly causing this issue is the distro-info package. You can try running the following and re-try your install:
`sudo python3 -m pip install --upgrade distro-info` and it should upgrade from 0.23ubuntu1 to 1.0, which will remove the errors you're seeing.

**Comment by calistouk** [comment]
Tried that and still getting the same error. 

[saltstack.zip](https://github.com/user-attachments/files/18134221/saltstack.zip)

**Comment by digitalsleuth** [comment]
Hi @calistouk , it looks like the upgrade didn't upgrade to version 1.0, but to another version with an incorrect naming structure. You can also attempt to uninstall the package via both the `apt` package manager (`sudo apt remove python3-distro-info`) and via `pip` (`sudo python3 -m pip uninstall distro-info`). 

After that, you can try the install again, and if you wish then reinstall the packages.

**Comment by ramirezrick** [comment]
I believe I have the same issue and tried your suggestion, but it still fails. Logs attached

> >> Running: ssh
> Update returned exit code not zero
> Error: Update returned exit code not zero
>     at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 
> 
> Sometimes problems occur due to network or server issues when
> downloading packages, in which case retrying your operation
> a bit later might lead to good results.




[saltstack.log.zip](https://github.com/user-attachments/files/18299530/saltstack.log.zip)

**Comment by digitalsleuth** [comment]
Hi @ramirezrick , it looks like the error in your situation was just a temporary connectivity issue:
```bash
# [DEBUG   ] Cannot perform 'http.query': https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar - [Errno -3] Temporary failure in name resolution
# [ERROR   ] Failed to cache https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar: Error: [Errno -3] Temporary failure in name resolution reading /iBotPeaches/apktool/downloads/apktool_2.9.3.jar
```

Other than this, everything else installed properly.

**Comment by ramirezrick** [comment]
> Hi @ramirezrick , it looks like the error in your situation was just a temporary connectivity issue:
> 
> ```shell
> # [DEBUG   ] Cannot perform 'http.query': https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar - [Errno -3] Temporary failure in name resolution
> # [ERROR   ] Failed to cache https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar: Error: [Errno -3] Temporary failure in name resolution reading /iBotPeaches/apktool/downloads/apktool_2.9.3.jar
> ```
> 
> Other than this, everything else installed properly.

Got it. I’m using NextDNS and one of the feed was blocking bbuseruploads.s3.amazonaws.com. Once I added it to the allow list, it installed successfully. 

Thank you.

**Comment by aloibeth** [comment]
Also having an issue with a new install... 

emnux@remnux:~$ remnux upgrade
> remnux-cli@1.3.9.1.g849ae31
> remnux-version: v2024.41.3

> downloading v2025.1.1

....

[saltstack.zip](https://github.com/user-attachments/files/18326095/saltstack.zip)

**Comment by digitalsleuth** [comment]
Hi @aloibeth , it looks like there was a temporary server issue when attempting to download `mitmproxy`:
```bash
# [ERROR   ] Failed to cache http://snapshots.mitmproxy.org/6.0.2/mitmproxy-6.0.2-linux.tar.gz: Error: HTTP 503: Service Unavailable reading /6.0.2/mitmproxy-6.0.2-linux.tar.gz
```

Everything else seems to have installed correctly though.
