### ISSUE TITLE
Error when running 'remnux upgrade' command on Remnux Virtualbox

### ISSUE THREAD

**Issue by InfoSecLuca** [REMnux/remnux-cli#29]
I am facing an issue with Remnux Ubuntu 20.04 (Focal) VirtualBox OVA (remnux-v7-focal-virtualbox.ova).
I was trying to update the Remnux machine using the `remnux upgrade` command but it always get this error:
```
>> Running: bluetooth
>> Running: docker
>> Running: /usr/local/bin/docker
>> Running: apt-get autoremove -y
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: away-from-the-dog
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:568:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```

The last few lines of the `/var/cache/remnux/cli/v2021.18.1/saltstack.log` file are:
```
test_|-remnux-python3-packages_|-remnux-python3-packages_|-nop:
    __id__: remnux-python3-packages
    __run_num__: 405
    __sls__: remnux.python3-packages
    changes: {}
    comment: Success!
    duration: 2.636
    name: remnux-python3-packages
    result: true
    start_time: '10:48:53.473214'
  test_|-remnux-repos_|-remnux-repos_|-nop:
    __id__: remnux-repos
    __run_num__: 14
    __sls__: remnux.repos
    changes: {}
    comment: Success!
    duration: 2.352
    name: remnux-repos
    result: true
    start_time: '10:39:03.895837'
  test_|-remnux-rubygems_|-remnux-rubygems_|-nop:
    __id__: remnux-rubygems
    __run_num__: 410
    __sls__: remnux.rubygems
    changes: {}
    comment: Success!
    duration: 7.627
    name: remnux-rubygems
    result: true
    start_time: '10:48:56.539814'
  test_|-remnux-scripts_|-remnux-scripts_|-nop:
    __run_num__: 528
    __sls__: remnux.scripts
    changes: {}
    comment: 'One or more requisite failed: remnux.scripts.ex_pe_xor.remnux-scripts-ex_pe_xor-source'
    duration: 0.007
    result: false
    start_time: '10:50:14.534777'
  test_|-remnux-theme-core_|-remnux-theme-core_|-nop:
    __id__: remnux-theme-core
    __run_num__: 713
    __sls__: remnux.theme.core.init
    changes: {}
    comment: Success!
    duration: 9.423
    name: remnux-theme-core
    result: true
    start_time: '10:51:12.428216'
  test_|-remnux-theme-gnome-config_|-remnux-theme-gnome-config_|-nop:
    __id__: remnux-theme-gnome-config
    __run_num__: 737
    __sls__: remnux.theme.gnome-config.init
    changes: {}
    comment: Success!
    duration: 10.101
    name: remnux-theme-gnome-config
    result: true
    start_time: '10:51:13.790560'
  test_|-remnux-theme_|-remnux-theme_|-nop:
    __id__: remnux-theme
    __run_num__: 759
    __sls__: remnux.theme
    changes: {}
    comment: Success!
    duration: 16.463
    name: remnux-theme
    result: true
    start_time: '10:51:21.539230'
  test_|-remnux-tools_|-remnux-tools_|-nop:
    __id__: remnux-tools
    __run_num__: 700
    __sls__: remnux.tools
    changes: {}
    comment: Success!
    duration: 2.273
    name: remnux-tools
    result: true
    start_time: '10:50:48.239213'
  user_|-remnux-user-remnux_|-remnux_|-present:
    __id__: remnux-user-remnux
    __run_num__: 348
    __sls__: remnux.config.user
    changes: {}
    comment: User remnux is present and up to date
    duration: 4.419
    name: remnux
    result: true
    start_time: '10:47:24.932382'
  virtualenv_|-remnux-python-packages-vipermonkey-virtualenv_|-/opt/vipermonkey_|-managed:
    __id__: remnux-python-packages-vipermonkey-virtualenv
    __run_num__: 232
    __sls__: remnux.python-packages.vipermonkey
    changes: {}
    comment: virtualenv exists
    duration: 3171.142
    name: /opt/vipermonkey
    result: true
    start_time: '10:40:34.561331'
  virtualenv_|-remnux-python3-packages-malwoverview-virtualenv_|-/opt/malwoverview_|-managed:
    __id__: remnux-python3-packages-malwoverview-virtualenv
    __run_num__: 349
    __sls__: remnux.python3-packages.malwoverview
    changes: {}
    comment: virtualenv exists
    duration: 2766.814
    name: /opt/malwoverview
    result: true
    start_time: '10:47:24.948039'
```
You can find in the file attached the saltstack.log file

[saltstack.log](https://github.com/REMnux/remnux-cli/files/6489462/saltstack.log)

I did try also to reboot the machine and to run `sudo apt update`, `sudo apt autoremove` and `sudo apt --fix-broken install` as suggested on the documentation but nothing changed.

Please let me know if you have any suggestion to fix this issue.

**Comment by lennyzeltser** [comment]
A few days ago an issue appeared with pefile, which is being tracked [here](https://github.com/erocarrera/pefile/issues/318). In the meantime, you can continue using your REMnux system despite this error.

**Comment by lennyzeltser** [comment]
@LucSai, @digitalsleuth submitted a [temporary fix](https://github.com/REMnux/salt-states/pull/179) to the pefile issue. The REMnux installer/upgrader should now complete without issues.
