### ISSUE TITLE
Error when running 'remnux upgrade' command

### ISSUE THREAD

**Issue by slpycatzz** [REMnux/remnux-cli#33]
I am trying to execute ```remnux upgrade``` command on a fresh installation but I encountered the following error:

```
...
>> Running: /etc/apt/apt.conf.d/20auto-upgrades
>> Running: bluetooth
>> Running: docker
>> Running: /usr/local/bin/docker
>> Running: apt-get autoremove -y
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: away-from-the-dog
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```

I have attached the [saltstack.log](https://github.com/REMnux/remnux-cli/files/6565980/saltstack.log)

I ran the following command ```grep -ai -B 8 -C 8 'result: false' saltstack.log``` on the file and noticed multiple ```result: false``` instances. The most prominent ones seems to be related to volatility plugins.

For completeness, I did a reboot, and ran ```sudo apt update``` , ```sudo apt autoremove``` and ```sudo apt --fix-broken install```. The problem persist.

I'm running on VMWare Fusion 12.1.4.

**Comment by digitalsleuth** [comment]
This seems to be another issue with pefile. @slpycatzz , can you tell me when you started the upgrade?

**Comment by lennyzeltser** [comment]
@digitalsleuth, I was able to reproduce this issue attempting to apply the remnux.python-packages.pefile state file  in a salt-tester container on Bionic. (This wasn't an issue on Focal.)

```
          ID: remnux-python-packages-pefile
    Function: pip.installed
        Name: pefile
      Result: False
     Comment: Failed to install packages: pefile. Error: Collecting pefile
                Downloading https://files.pythonhosted.org/packages/f9/1e/fc4fac0169d16a98577809400bbcfac8ad1900fa792184327b360ea51fc6/pefile-2021.5.13.tar.gz (66kB)
                  Complete output from command python setup.py egg_info:
                  Traceback (most recent call last):
                    File "<string>", line 1, in <module>
                    File "/tmp/pip-build-k4pCU_/pefile/setup.py", line 86, in <module>
                      long_description = "\n".join(_read_doc().split('\n')),
                    File "/tmp/pip-build-k4pCU_/pefile/setup.py", line 30, in _read_doc
                      tree = ast.parse(f.read())
                    File "/usr/lib/python2.7/ast.py", line 37, in parse
                      return compile(source, filename, mode, PyCF_ONLY_AST)
                    File "<unknown>", line 3789
                      f'Export directory contains more than 10 repeated entries '
                                                                                ^
                  SyntaxError: invalid syntax
                  
                  ---------------------------------------- Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k4pCU_/pefile/
```

**Comment by digitalsleuth** [comment]
I think I know why. I'll look into it right away.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by slpycatzz** [comment]
I started the upgrade around 8 hours ago, which is around 6:00am UTC.

**Comment by lennyzeltser** [comment]
Thanks @slpycatzz for reporting this and @digitalsleuth for [fixing this](https://github.com/REMnux/salt-states/pull/184).
