### ISSUE TITLE
Problem installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by usernop1** [REMnux/remnux-cli#4]
Hello, I would like to ask for a hint on an issue I'm experimenting with remnux-cli.

After downloading the installer and adding the remnux user on Linux, I run:

    sudo remnux install

But it stops at this point (using installer version 2020.30.9, 2020.30.10 and 2020.31.1:

````
>> Running: docker
>> Running: /usr/local/bin/docker
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: away-from-the-dog
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:550:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)

````

The file saltstack.log ends with the following lines:

````
  test_|-remnux-tools_|-remnux-tools_|-nop:
    __run_num__: 599
    __sls__: remnux.tools
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-wrapper,
      remnux.tools.polarproxy.remnux-polarproxy-archive, remnux.tools.polarproxy.remnux-polarproxy-source,
      remnux.tools.polarproxy./usr/local/polarproxy/PolarProxy'
    duration: 0.031
    result: false
    start_time: '20:16:05.944022'
  user_|-remnux-user-remnux_|-remnux_|-present:
    __id__: remnux-user-remnux
    __run_num__: 343
    __sls__: remnux.config.user
    changes: {}
    comment: User remnux is present and up to date
    duration: 2.136
    name: remnux
    result: true
    start_time: '19:54:38.200820'
  virtualenv_|-remnux-python-packages-viper-virtualenv_|-/opt/viper_|-managed:
    __id__: remnux-python-packages-viper-virtualenv
    __run_num__: 326
    __sls__: remnux.python-packages.viper-framework
    changes: {}
    comment: virtualenv exists
    duration: 12727.466
    name: /opt/viper
    result: true
    start_time: '19:54:05.177568'
  virtualenv_|-remnux-python-packages-vipermonkey-virtualenv_|-/opt/vipermonkey_|-managed:
    __id__: remnux-python-packages-vipermonkey-virtualenv
    __run_num__: 280
    __sls__: remnux.python-packages.vipermonkey
    changes: {}
    comment: virtualenv exists
    duration: 9194.201
    name: /opt/vipermonkey
    result: true
    start_time: '19:52:03.475586'

````

And finally the grep for ERROR:

    grep ERROR /var/cache/remnux/cli/v2020.31.1/saltstack.log

````
# [ERROR   ] Can't parse line 'vipermonkey @ git+https://github.com/decalage2/ViperMonkey.git@511ecd59d54c6a3424178af6b99e4c1f699274c4'
# [ERROR   ] Command '[u'git', u'config', u'--global', u'--get-regexp', u'filter\\.lfs\\.']' failed with return code: 1
# [ERROR   ] retcode: 1
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@937a19e00ed6b59f9d0cd732f9f9c665b745e2a8'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@937a19e00ed6b59f9d0cd732f9f9c665b745e2a8'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@937a19e00ed6b59f9d0cd732f9f9c665b745e2a8'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@937a19e00ed6b59f9d0cd732f9f9c665b745e2a8'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@937a19e00ed6b59f9d0cd732f9f9c665b745e2a8'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@937a19e00ed6b59f9d0cd732f9f9c665b745e2a8'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@937a19e00ed6b59f9d0cd732f9f9c665b745e2a8'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
Binary file /var/cache/remnux/cli/v2020.31.1/saltstack.log matches
````

I'm not familiar with SaltStack. I would much appreciate any help on this.

Thank you in advance!!

**Comment by lennyzeltser** [comment]
Have you tried rebooting your system and then running the `remnux` command again?

**Comment by sidomir7** [comment]
Hi, I have similar problem. 
I installed Ubuntu 18.04 Desktop 64-bit Virtual machine. 
Then I download remnux-cli with help of this [guide](https://docs.remnux.org/install-distro/add-to-existing-system)
Before installation I fully updated Ubuntu 
I used command `sudo remnux install --mode=addon`
Installation end with this 
```

>> Running: remnux-tools
>> Running: remnux-node-packages
>> Running: cpan install Image::ExifTool
>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:550:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
```
 

I restarted VM and same issue occurred. 
Here are the ERRORs from saltstack.log


```
# [ERROR   ] Command '[u'apt-key', u'adv', u'--batch', u'--keyserver', u'keyserver.ubuntu.com', u'--logger-fd', u'1', u'--recv-keys', u'D3D831EF']' failed with return code: 2
# [ERROR   ] stdout: Executing: /tmp/apt-key-gpghome.6X1XtBt40M/gpg.1.sh --batch --keyserver keyserver.ubuntu.com --logger-fd 1 --recv-keys D3D831EF
# [ERROR   ] stderr: Warning: apt-key output should not be parsed (stdout is not a terminal)
# [ERROR   ] retcode: 2
# [ERROR   ] Failed to configure repo 'deb https://download.mono-project.com/repo/ubuntu stable-bionic main': Error: key retrieval failed: Executing: /tmp/apt-key-gpghome.6X1XtBt40M/gpg.1.sh --batch --keyserver keyserver.ubuntu.com --logger-fd 1 --recv-keys D3D831EF
# [ERROR   ] Can't parse line 'vipermonkey @ git+https://github.com/decalage2/ViperMonkey.git@511ecd59d54c6a3424178af6b99e4c1f699274c4'
# [ERROR   ] Command '[u'git', u'config', u'--global', u'--get-regexp', u'filter\\.lfs\\.']' failed with return code: 1
# [ERROR   ] retcode: 1
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@65c509b70e35e0c746b934298360cdb242cc8d12'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@65c509b70e35e0c746b934298360cdb242cc8d12'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@65c509b70e35e0c746b934298360cdb242cc8d12'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@65c509b70e35e0c746b934298360cdb242cc8d12'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@65c509b70e35e0c746b934298360cdb242cc8d12'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@65c509b70e35e0c746b934298360cdb242cc8d12'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
# [ERROR   ] Can't parse line 'pymispgalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git@5645225fae5534b27f456f3b1d62262ba586b46b'
# [ERROR   ] Can't parse line 'pytaxonomies @ git+https://github.com/MISP/PyTaxonomies.git@078cee3427faaff5bc935aeae489382452d62089'
# [ERROR   ] Can't parse line 'scrapysplashwrapper @ git+https://github.com/viper-framework/ScrapySplashWrapper.git@65c509b70e35e0c746b934298360cdb242cc8d12'
# [ERROR   ] Can't parse line 'verify-sigs @ git+https://github.com/sebdraven/verify-sigs.git@a94e78c1bc7256a76a84f51049d73517f359b979'
# [ERROR   ] Can't parse line 'xxxswf @ git+https://github.com/viper-framework/xxxswf.git@9188316eb7a179326d99bfde9fe0184bb3cee6a3'
```

**Comment by lennyzeltser** [comment]
@sidomir7, in your case, the issue seems to be the inability of the installer to retrieve the mono-project GPG key from the Ubuntu key server. I've seen such issues sometimes due to the server's load issues. I'm wondering whether you are able to add the key manually using this command:

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D3D831EF
```

The other errors in the log file for `vipermonkey` and `Can't parse line` don't actually present an issue, and are common.

**Comment by sidomir7** [comment]
@lennyzeltser, it is working now Thank You

**Comment by usernop1** [comment]
Hello, I tried today with version 2020.31.4 and (rebooted) it did not work. The point of failure is the same (when ````>> Running: ssh```` ). I forgot to mention that this is a Qubes VM running Ubuntu 18.04, in case it matters.

Thank you in advance,

**Comment by usernop1** [comment]
This time, these error messages arise as well:
````
remnux@remnux:~$ grep ERROR /var/cache/remnux/cli/v2020.31.4/saltstack.log 
# [ERROR   ] An exception occurred in this state: Traceback (most recent call last):
# [ERROR   ] Command '['apt-get', '-q', 'update']' failed with return code: 100
# [ERROR   ] stdout: Reading package lists...
# [ERROR   ] stderr: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
# [ERROR   ] retcode: 100
# [ERROR   ] E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
# [ERROR   ] Command '['/usr/bin/python3', '-m', 'pip', 'install', '--disable-pip-version-check', 'requesocks']' failed with return code: 1
# [ERROR   ] stdout: Collecting requesocks
# [ERROR   ] stderr: The directory '/home/remnux/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
# [ERROR   ] retcode: 1
# [ERROR   ] Failed to install packages: requesocks. Error: Collecting requesocks
# [ERROR   ] Can't parse line 'vipermonkey @ git+https://github.com/decalage2/ViperMonkey.git@511ecd59d54c6a3424178af6b99e4c1f699274c4'
# [ERROR   ] Command '['git', 'config', '--global', '--get-regexp', 'filter\\.lfs\\.']' failed with return code: 1
# [ERROR   ] retcode: 1
# [ERROR   ] Command '['/usr/bin/python3', '-m', 'pip', 'install', '--disable-pip-version-check', 'balbuzard']' failed with return code: 1
# [ERROR   ] stdout: Collecting balbuzard
# [ERROR   ] stderr: The directory '/home/remnux/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
# [ERROR   ] retcode: 1
# [ERROR   ] Failed to install packages: balbuzard. Error: Collecting balbuzard
````

**Comment by lennyzeltser** [comment]
@usernop1, we released new versions of the REMnux installer and state-files tonight. They aren't designed to address installation issues directly, but it's worth giving them a try.

Could you please do the following:

1. Go back to the clean state of your system before you tried installing REMnux.
2. Reboot it.
3. Download the new REMnux installer (remnux-cli) and run the installation.

If the installation doesn't succeed, please attach the full saltstack.log file to this thread. Making sense of that log file is tricky, because sometimes what is there as an "ERROR" isn't actually an error. In your most recent report, the `Could not get lock /var/lib/apt/lists/lock` message is an error, and I found that rebooting the system before trying the installation addresses that particular problem.

**Comment by usernop1** [comment]
@lennyzeltser, the first try on a fresh vm newly created, did not succeed and it took more than 8 hours (I'm attaching the log file for this try), and in between it seems you released a new version of the installer. Therefore, after the reboot, the second try is running with the new version: v2020.31.12.
Now it appears that since an hour ago, the installer is stuck in ````>> Running: /usr/local/bin/cutter```` while the logfile's tail is currently this:
````
# [DEBUG   ] Could not LazyLoad file.mod_watch: 'file.mod_watch' is not available.
# [INFO    ] Running state [/usr/local/bin/cfr] at time 09:08:43.794619
# [INFO    ] Executing state file.managed for [/usr/local/bin/cfr]
# [INFO    ] File /usr/local/bin/cfr is in the correct state
# [INFO    ] Completed state [/usr/local/bin/cfr] at time 09:08:43.813721 (duration_in_ms=19.102)
# [INFO    ] Running state [/usr/local/bin/cutter] at time 09:08:43.814004
# [INFO    ] Executing state file.managed for [/usr/local/bin/cutter]
# [DEBUG   ] Requesting URL https://github.com/radareorg/cutter/releases/download/v1.11.0/Cutter-v1.11.0-x64.Linux.AppImage using GET method
# [DEBUG   ] Using backend: tornado
````

I could probably say that when appears the message ````# [DEBUG   ] Using backend: tornado````, that operation takes a long time, but I'm not familiar with SaltStack and don't know how to properly debug the process.

I'll update with more info when the installation finishes. 
Regards,

**Comment by usernop1** [comment]
[saltstack.log.1.zip](https://github.com/REMnux/remnux-cli/files/5010389/saltstack.log.1.zip)

**Comment by usernop1** [comment]
Well, this time things went so much faster than the previous try, but the installation did not succeed again.
I'm attaching the log file for this second try after the reboot. Hope this helps. 
If I can do anything to help testing, just let me know.

Thank you,

[saltstack.log.zip](https://github.com/REMnux/remnux-cli/files/5010481/saltstack.log.zip)

**Comment by lennyzeltser** [comment]
@usernop1, thanks for sharing the log file, it helps. I see a number of "Connection timed out" messages tied to some of the larger downloads (e.g., Burp Suite and PolarProxy. I believe that's what is causing your most recent issues. Another indicator that the connectivity is the problem is that the initial install took so many hours. 

If switching to a faster internet connection isn't practical, you could continue using the distro as is, without these tools, and running `remnux update` later in case the network gets to a better state. Another option is to start with the REMnux OVA file, which will have these tools preinstalled.
