### ISSUE TITLE
From scratch install not working - Ubuntu Focal 20.04 

### ISSUE THREAD

**Issue by brymon68** [REMnux/remnux-cli#41]
```
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```

Saltstack.log attached
[saltstack.log](https://github.com/REMnux/remnux-cli/files/6985013/saltstack.log)

**Comment by lennyzeltser** [comment]
Thanks for reporting the issue, @brymon68. There was a problem with Speakeasy, which I now corrected. The other tools installed fine, so you don't need to reinstall REMnux if you don't want to. You can just run `remnux upgrade`.
