### ISSUE TITLE
Install from scratch fails on Xubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by zoerab** [REMnux/remnux-cli#55]
Trying to install from scratch on Xubuntu VM but installer fails every time.

### Distro info/version

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

### Error itself

while trying to run `sudo remnux install`

```
> remnux-cli@1.3.3.0.g1df38b1
> remnux-version: notinstalled

> downloading v2021.45.1
>> downloading remnux-salt-states-v2021.45.1.tar.gz.asc
>> downloading remnux-salt-states-v2021.45.1.tar.gz.sha256
>> downloading remnux-salt-states-v2021.45.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2021.45.1.tar.gz
> validating file remnux-salt-states-v2021.45.1.tar.gz
> validating signature for remnux-salt-states-v2021.45.1.tar.gz.sha256
> extracting update remnux-salt-states-v2021.45.1.tar.gz
> no previous REMnux version found; performing a new 'dedicated' installation.
> upgrading/updating to v2021.45.1
>> Log file: /var/cache/remnux/cli/v2021.45.1/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

```
### Content of saltstack.log

```


[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: poisonbox
# [DEBUG   ] Configuration file path: /etc/salt/minion
# [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
# [DEBUG   ] Grains refresh requested. Refreshing grains.
# [DEBUG   ] Missing configuration file: /etc/salt/minion
# [DEBUG   ] Elapsed time getting FQDNs: 0.03252220153808594 seconds
# [ERROR   ] An un-handled exception was caught by salt's global exception handler:
CommandExecutionError: The shell zsh is not available
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3001.8', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 64, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 329, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 89, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 912, in __init__
    opts["grains"] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 825, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2083, in os_data
    grains.update(_linux_gpu_data())
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 225, in _linux_gpu_data
    lspci_out = __salt__["cmd.run"]("{0} -vmm".format(lspci))
  File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 883, in _run_quiet
    return _run(
  File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 345, in _run
    raise CommandExecutionError(msg)
salt.exceptions.CommandExecutionError: The shell zsh is not available
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3001.8', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 64, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 329, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 89, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 912, in __init__
    opts["grains"] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 825, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2083, in os_data
    grains.update(_linux_gpu_data())
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 225, in _linux_gpu_data
    lspci_out = __salt__["cmd.run"]("{0} -vmm".format(lspci))
  File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 883, in _run_quiet
    return _run(
  File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 345, in _run
    raise CommandExecutionError(msg)
salt.exceptions.CommandExecutionError: The shell zsh is not available
```

For some reason installer seem to fail to locate zsh which is present (installed it myself) and at a version: zsh 5.8 (x86_64-ubuntu-linux-gnu)

Anyone seen this before?

**Comment by digitalsleuth** [comment]
@zoerab Can you tell me how you built your Xubuntu VM so I can test it out? This should include all the packages you added to the VM as well before running the CLI.

**Comment by zoerab** [comment]
@digitalsleuth 
Thank you for such a swift reply.

I've only installed following extra's: neovim, vim, zsh, tmux, git, htop, curl, gnupg
VM itself was built from the latest ISO of Xubuntu (xubuntu-20.04.3-desktop-amd64.iso)

VM specs in VirtualBox are as follow:

CPU: 2 virtual CPU with 100% cap
RAM: 4096 Mb
HDD: 80 Gb (SATA controller)
NET: (tried both NAT and Bridged)

Let me know if you need more info

**Comment by digitalsleuth** [comment]
When you installed zsh, did you run it and configure it? Or did you just install it?

**Comment by zoerab** [comment]
Now that you mention it, yes I did install https://github.com/romkatv/powerlevel10k
As well as OhMyZsh (https://github.com/romkatv/powerlevel10k#oh-my-zsh)

Along with a preconfigured dotfiles from my own repo (use it all the time).

**Comment by digitalsleuth** [comment]
Aside from the dotfiles, can you identify which theme you enabled and what method you used to install?

**Comment by zoerab** [comment]
Theme I use I've configured some time ago (initially configured powerlevel10k via their default wizard and changed some colors later manually).

https://github.com/zoerab/dotfiles/blob/master/zsh/.p10k.zsh

**Comment by zoerab** [comment]
Quick update.
I've reinstalled Xubuntu from the same image but this time I've only run an update of the system (apt upgrade) and moved directly to installation of remnux (from scratch) as per official documentation. So far, the installer is RUNNING!!!

Will keep you guys posted

**Comment by zoerab** [comment]
![image](https://user-images.githubusercontent.com/9844177/144766239-31585247-844c-4047-8bb6-2a07536ee526.png)

**Comment by digitalsleuth** [comment]
I managed to complete a successful install by following this method:
- Install Xubuntu and `sudo apt-get update && sudo apt-get upgrade -y`
- sudo apt-get install zsh
- `zsh`
- Configure zsh with minimal config (blank .zshrc)
- `exit`
- `sudo wget -O /usr/local/bin/remnux https://github.com/remnux/remnux-cli/releases/download/v1.3.3/remnux-cli-linux`
- `sudo chmod +x /usr/local/bin/remnux`
- `sudo remnux install --mode dedicated`

Now, I haven't tried installing powerlevel or OhMyZsh, so perhaps that might make a difference, but I'm guessing that, if you didn't launch zsh after installing, that saltstack may not have been able to launch the shell as expected.

**Comment by zoerab** [comment]
@digitalsleuth 
Thank you for your effort in troubleshooting this! I've reinstalled Xubuntu and Remnux and it runs without any issues now!
