### ISSUE TITLE
Salt stack fails to install remnux-theme

### ISSUE THREAD

**Issue by Xboarder56** [REMnux/remnux-cli#73]
Getting the following error trying to install Remnux on a fresh Ubuntu 20.04.4 LTS build. 

```>> Running: remnux-theme
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.```

**Comment by digitalsleuth** [comment]
Hi @Xboarder56 , can you upload your saltstack.log file so we can review to find the cause of the error?

**Comment by Xboarder56** [comment]
@digitalsleuth just pulled the regex of it from the docs (will work to grab the raw log):

```grep -i -C 5 'result: false' or grep -i -B 8 'result: false' /var/cache/remnux/cli/v2022.16.1/saltstack.log 
grep: or: No such file or directory
grep: grep: No such file or directory
grep: result: false: No such file or directory
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    result: true
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    start_time: '09:17:38.198530'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-  file_|-remnux-addon-version-file_|-/etc/remnux-version_|-managed:
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __run_num__: 756
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __sls__: remnux.addon
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    changes: {}
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    comment: 'One or more requisite failed: remnux.scripts.remnux-scripts'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    duration: 0.006
/var/cache/remnux/cli/v2022.16.1/saltstack.log:    result: false
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    start_time: '09:58:02.572802'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-  file_|-remnux-config-android-project-creator-permissions_|-/opt/AndroidProjectCreator/library_|-directory:
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __id__: remnux-config-android-project-creator-permissions
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __run_num__: 657
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __sls__: remnux.config.android-project-creator
--
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    result: true
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    start_time: '09:56:08.614633'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-  file_|-remnux-pyinstaller-shebang_|-/usr/local/bin/pyinstxtractor.py_|-prepend:
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __run_num__: 458
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __sls__: remnux.scripts.pyinstaller-extractor
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    changes: {}
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    comment: 'One or more requisite failed: remnux.scripts.pyinstaller-extractor.remnux-pyinstaller-source'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    duration: 0.005
/var/cache/remnux/cli/v2022.16.1/saltstack.log:    result: false
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    start_time: '09:50:07.567814'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-  file_|-remnux-pyinstaller-source_|-/usr/local/bin/pyinstxtractor.py_|-managed:
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __id__: remnux-pyinstaller-source
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __run_num__: 457
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __sls__: remnux.scripts.pyinstaller-extractor
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    changes: {}
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    comment: Specified sha256 checksum for /usr/local/bin/pyinstxtractor.py (6b0e61f5321e4b00b07ae487515fca5f471a9d96c7bd393fcb6472fed2d8fc75)
/var/cache/remnux/cli/v2022.16.1/saltstack.log-      does not match actual checksum (b16712bcc9e727b66c1041792a535b76c023ea7b106173016df20735cf31b706)
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    duration: 709.568
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    name: /usr/local/bin/pyinstxtractor.py
/var/cache/remnux/cli/v2022.16.1/saltstack.log:    result: false
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    start_time: '09:50:06.565412'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-  file_|-remnux-python-packages-droidlysis-droidconfig-set1_|-/usr/local/lib/python3.8/dist-packages/droidconfig.py_|-replace:
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __id__: remnux-python-packages-droidlysis-droidconfig-set1
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __run_num__: 360
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __sls__: remnux.python3-packages.droidlysis
--
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    result: true
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    start_time: '09:58:50.146389'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-  test_|-remnux-cloud_|-remnux-cloud_|-nop:
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __run_num__: 812
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __sls__: remnux.cloud
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    changes: {}
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    comment: 'One or more requisite failed: remnux.addon.remnux-addon-version-file'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    duration: 0.003
/var/cache/remnux/cli/v2022.16.1/saltstack.log:    result: false
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    start_time: '09:58:52.399503'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-  test_|-remnux-config-salt-minion-placeholder_|-remnux-config-salt-minion-placeholder_|-nop:
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __id__: remnux-config-salt-minion-placeholder
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __run_num__: 598
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __sls__: remnux.config.salt-minion
--
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    start_time: '09:49:45.461992'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-  test_|-remnux-scripts_|-remnux-scripts_|-nop:
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __run_num__: 570
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __sls__: remnux.scripts
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    changes: {}
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    comment: 'One or more requisite failed: remnux.scripts.pyinstaller-extractor.remnux-pyinstaller-shebang,
/var/cache/remnux/cli/v2022.16.1/saltstack.log-      remnux.scripts.pyinstaller-extractor.remnux-pyinstaller-source'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    duration: 0.007
/var/cache/remnux/cli/v2022.16.1/saltstack.log:    result: false
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    start_time: '09:51:18.167738'
/var/cache/remnux/cli/v2022.16.1/saltstack.log-  test_|-remnux-theme-core_|-remnux-theme-core_|-nop:
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __id__: remnux-theme-core
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __run_num__: 763
/var/cache/remnux/cli/v2022.16.1/saltstack.log-    __sls__: remnux.theme.core.init
```

**Comment by Xboarder56** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8592709/saltstack.log)

Attached the salt log.

**Comment by digitalsleuth** [comment]
From what you've posted, it looks like pyinstaller-extractor has been updated and requires a new hash. I'll review the rest of the saltstack.log as well for any other errors!

**Comment by Xboarder56** [comment]
Awesome, thanks for the quick response @digitalsleuth and the assistance is greatly appreciated!

**Comment by digitalsleuth** [comment]
@Xboarder56 It looks like it's just the hash that was the problem. Everything else in your installation has installed correctly. I've submitted a [PR](https://github.com/REMnux/salt-states/pull/210) to update the hash, so this issue will be resolved for the next release.

**Comment by lennyzeltser** [comment]
I just issued a new REMnux release that includes @digitalsleuth's fix.

**Comment by Xboarder56** [comment]
Thanks guys, just confirmed it finished the install successfully with the latest patch.
