### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by gdolsson** [REMnux/remnux-cli#78]
First of all, love the OS. All the tools in a single place for easy install! Really great work, appreciated

I've been experiencing the same issues as reported by others, problem with keys, something with python, incorrect hashes and now this:

```
remnux upgrade
> remnux-cli@1.3.3.0.g1df38b1
> remnux-version: v2022.7.1

Installing and configuring SaltStack properly ...

Command failed: wget -O - https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3001/salt-archive-keyring.gpg | apt-key add -
--2022-05-20 23:19:14--  https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3001/salt-archive-keyring.gpg
Resolving repo.saltproject.io (repo.saltproject.io)... 13.33.138.4, 13.33.138.17, 13.33.138.34, ...
Connecting to repo.saltproject.io (repo.saltproject.io)|13.33.138.4|:443... connected.
HTTP request sent, awaiting response... Warning: apt-key output should not be parsed (stdout is not a terminal)
404 Not Found
2022-05-20 23:19:15 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.

Error: Command failed: wget -O - https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3001/salt-archive-keyring.gpg | apt-key add -
--2022-05-20 23:19:14--  https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3001/salt-archive-keyring.gpg
Resolving repo.saltproject.io (repo.saltproject.io)... 13.33.138.4, 13.33.138.17, 13.33.138.34, ...
Connecting to repo.saltproject.io (repo.saltproject.io)|13.33.138.4|:443... connected.
HTTP request sent, awaiting response... Warning: apt-key output should not be parsed (stdout is not a terminal)
404 Not Found
2022-05-20 23:19:15 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```
Feels like there is a larger issue, tried the suggested "fixes" in the docs and as suggested here. Still can't update.

I'm running in virtualbox based off of an official "image"

**Comment by digitalsleuth** [comment]
Hi @gdolsson , it's great to hear that you're getting value and enjoyment out of the REMnux suite! The error you're experiencing can be resolved by upgrading the CLI using the instructions found [here](https://github.com/REMnux/remnux-cli/releases/tag/v1.3.4). Once upgraded, please reun the upgrade command and the issue should be resolved.

Cheers!
