### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by gunner4361** [REMnux/remnux-cli#80]
var/cache/remnux/cli/v2022.20.8# more saltstack.log 
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3004.1', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 426, in salt_call
    import salt.cli.call
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 3, in <module>
    import salt.cli.caller
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 15, in <module>
    import salt.minion
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 35, in <module>
    import salt.pillar
  File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 15, in <mo
dule>
    import salt.fileclient
  File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 30, in <module>
    import salt.utils.templates
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 20, in <mo
dule>
    import salt.utils.jinja
  File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 28, in <module
>
    from jinja2 import BaseLoader, Markup, TemplateNotFound, nodes
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python
/dist-packages/jinja2/__init__.py)

Not sure how to fix this, Please help

**Comment by digitalsleuth** [comment]
Hi @gunner4361 , if you already have the latest remnux-cli, then you can simply run `sudo python3 -m pip install jinja2==3.0.3` and you should be good to go. The newest version of SaltStack unfortunately updates Jinja2 which causes the problem, but after running the above, and the remnux CLI, you'll be pinned at the supported version of Jinja2 and shouldn't have a problem.

**Comment by digitalsleuth** [comment]
Hi @gunner4361, have you had any success with this?

**Comment by Qbert777** [comment]
Just wanted to report that I had this error and the provided fix worked for me.
Thanks!
